Makefile
Prior to this change, message was printed like this:
```bash
$ make publish DRY_RUN=true
...
Install sass first. For OSX: brew install sass/sass/sassmake: *** [build-linkerd.io] Error 1
```
=> Fix brew warnings in Makefile

Makefile, README.md
Support serving any of the *.linkerd.io websites, notably this allows
testing versioncheck.linkerd.io against the latest publicly available
Linkerd2 release.
=> Support for `make serve-*.linkerd.io`

Makefile, linkerd.io/config.toml, run.linkerd.io/public/install, versioncheck.linkerd.io/public/version.json
This branch replaces the `L5D2_LATEST_VERSION` var with 2 separate vars for 2 separate release channels: `L5D2_STABLE_VERSION` and `L5D2_EDGE_VERSION`.
As part of this branch I'm removing the code to publish the site to version-specific buckets, since we weren't using it and it would be more complicated to update it to work with multiple different release channels.
=> Setup repo for multiple version channels

linkerd.io/content/1/getting-started/ecs.md
This updates the ECS getting started guide to use CloudFormation templates for an easier LinkerD deploy experience, and simplifies and secures the deployment approach by using the latest daemon service support in ECS
=> Refreshing the ECS getting started guide with latest features

linkerd.io/content/2/edge/_index.md, linkerd.io/content/2/get-involved/_index.md, linkerd.io/content/2/proxy-injection/_index.md
This PR contains the documentation for the auto proxy injection feature. It includes instructions to install the proxy injector, testing the auto proxy injection and its current limitations.
I'm not sure if I'm doing this doc correctly as I am unable to run the hugo server locally, following the steps in the README.
=> Documentation for the auto proxy injection.

linkerd.io/content/2/cli/inject.mmark, linkerd.io/content/2/ha/_index.md
Started to add some basic HA for a new experimental flag to enable multiple controller replicas and sensible requests to the k8s deployments.
Pending on merge of https://github.com/linkerd/linkerd2/pull/1852.
Also not sure if this the right way to do documentation - I just didn't think it was fair that someone else had to document a feature that they maybe didn't build, so thought I should at least start it 👍 
Signed-off-by: Blam <ben@blam.sh>
=> Added some documentation for --ha flag to Linkerd2

linkerd.io/content/2/proxy-injection/_index.md
=> Fix spelling of linkerd.io in auto inject docs

linkerd.io/content/2/observability/prometheus.md
The existing Prometheus docs instructed users to collect from Linkerd
proxies directly.
Instead provides instructions for using Prometheus federation, a simpler
and more robust approach.
=> Modify Prometheus docs to use Federation

CONTRIBUTING.md, README.md, linkerd.io/config.toml, linkerd.io/layouts/alias.html, linkerd.io/layouts/index.html, linkerd.io/layouts/partials/cyp.html, linkerd.io/layouts/partials/footer.html, linkerd.io/layouts/partials/get-started.html, linkerd.io/layouts/partials/nav.html
Hugo's `ref` produces HTML with absolute links, causing many links
rendered via `make serve-linkerd.io` to point to linkerd.io rather than
localhost.
Replace `ref` with `relref`, also introduce an Alias partial, to override
default alias behavior with relative links.
=> Make all links relative

run.linkerd.io/public/booksapp.yml
Update the public booksapp.yml to install the app with sqlite3 backends instead of mysql. This drastically improves startup times, but means that we can only run 1 replica each of the books and authors deployments.
=> Update booksapp config to use in-memory storage

run.linkerd.io/public/emojivoto-daemonset.yaml
Add emojivoto daemonset yaml manifest to the run.linkerd.io public site.
This yaml contains web, voting, emoji, and vote-bot apps as DaemonSets.
Also includes emoji, voting and web Services and emojivoto Namespace
Signed-off-by: Zak Knill <zrjknill@gmail.com>
=> Add emojivoto daemonset yaml manifest

linkerd.io/content/2/automatic-tls/_index.md, linkerd.io/content/2/cli/_index.md, linkerd.io/content/2/cni/_index.md, linkerd.io/content/2/debugging/_index.md, linkerd.io/content/2/edge/_index.md, linkerd.io/content/2/faq/_index.md, linkerd.io/content/2/get-involved/_index.md, linkerd.io/content/2/ingress/_index.md, linkerd.io/content/2/observability/_index.md, linkerd.io/content/2/proxy-injection/_index.md, linkerd.io/content/2/supported-protocols/_index.md
This branch updates the proxy auto-inject doc to reflect the change in targeting behavior that's happening in linkerd/linkerd2#2209. As part of this change, I've trimmed down the content on the page a bit, to hopefully make it easier to follow.
Fixes #112.
=> Update auto-inject docs for new opt-in behavior

linkerd.io/content/2/upgrade/_index.md
Fixes #104 
Not only won't `linkerd version` work after upgrading the CLI (before upgrading the CP), but also `check`, `dashboard`, `stats`, etc.
=> Add note for 2.1.0 upgrade regarding the CLI

run.linkerd.io/public/booksapp.yml
This enables easy selection of all resources related to this demo.
Especially:
kubectl delete all -l project=booksapp
=> Add a `project` label to all booksapp resources

linkerd.io/content/1/tutorials/part-nine.md, linkerd.io/content/2/ha/_index.md, linkerd.io/content/2/observability/proxy-metrics.md
1. "availble" to "available" in line 59.
2. "Availabilty" to "Availability" in line 3.
3. "recieved" to "received" in line 171.
=> Fix some typos in docs

linkerd.io/content/2/faq/_index.md, linkerd.io/content/2/installing/_index.md
Move installation debugging content out of FAQ and into an Installing section.
Add new FAQ content.
This will require a change in the linkerd check output since the URLs have
updated.
=> improve faq and split out installation checks

linkerd.io/content/2/cli/check.md, linkerd.io/content/2/cli/routes.mmark, linkerd.io/static/checks/index.html
The `linkerd check` command references linkerd.io URLs with anchors, for
example:
https://linkerd.io/2/faq/#pre-k8s
Moving the location of `/2/faq` breaks these URLs, and hugo does not
persist anchors across alias redirects.
This change introduces a static page, allowing us to maintan aliases for
`linkerd check` output that preserves anchors.
Example redirect:
https://linkerd.io/checks/#pre-k8s -> https://linkerd.io/2/faq/#pre-k8s
This change was motivated by #146.
=> Add static checks page to redirect anchor links

linkerd.io/content/2/cli/routes.md, linkerd.io/data/cli.yaml
This PR updates the `linkerd routes` doc to use the recently introduced system for CLI docs.
=> Update routes doc

linkerd.io/content/2/features/_index.md, linkerd.io/content/2/features/automatic-tls.md, linkerd.io/content/2/features/cni.md, linkerd.io/content/2/features/dashboard.md, linkerd.io/content/2/features/ha.md, linkerd.io/content/2/features/http-grpc.md, linkerd.io/content/2/features/ingress.md, linkerd.io/content/2/features/load-balancing.md, linkerd.io/content/2/features/protocol-detection.md, linkerd.io/content/2/features/proxy-injection.md, linkerd.io/content/2/features/retries-and-timeouts.md, linkerd.io/content/2/features/service-profiles.md, linkerd.io/content/2/features/telemetry.md
This is a follow-up to #145, which setup a new features index page. The index page wasn't really using the `sectiontoc` shortcode correctly, so items were showing up out of order, and the features index page itself was being included in the list of features. This should fix it. Adding a `description` tag on each of the feature pages would also make the index page a lot prettier. I can add that as part of this branch if nobody else is working on it.
Before this branch, on current master, the feature index page looks like this:
And after this branch, it looks like this:
=> Fix ordering on feature index page

linkerd.io/content/2/cli/routes.md
This should be the last one under the CLI section.
=> Fix the 'retries and timeout' link

linkerd.io/assets/scss/custom.scss, linkerd.io/assets/scss/index.scss, linkerd.io/content/2/architecture/_index.md, linkerd.io/content/2/cli/check.md, linkerd.io/content/2/cli/inject.md, linkerd.io/content/2/cli/routes.md, linkerd.io/content/2/debugging/_index.md, linkerd.io/content/2/edge/_index.md, linkerd.io/content/2/faq/_index.md, linkerd.io/content/2/getting-started/_index.md, linkerd.io/content/2/observability/exporting-metrics.md, linkerd.io/content/2/observability/proxy-metrics.md, linkerd.io/data/cli.yaml, linkerd.io/layouts/partials/docs.html, linkerd.io/layouts/partials/flags.html, linkerd.io/layouts/shortcodes/cli.html
- Uses Roboto as the default font.
- Adds a border for h1/h2 to make them a little more readable.
- Converts the title into a display header to differentiate and reduce the header nesting.
- Moves the margin around for headers a little to reduce bottom padding and increase top padding a little.
- Fixes inline formatting to pop more during reading.
- Fixes CLI table formatting.
- Adds the ability to show a TOC at the top of a page (see the FAQ).
=> Style, topography and small content updates

linkerd.io/content/2/getting-started/_index.md
This should hopefully help to simplify the process of viewing the emojivoto app in your web browser.
=> Use simpler port-forwarding in getting started guide

linkerd.io/config.toml
This PR introduces a more Hugo-native way to disable taxonomies for the linkerd.io site
=> Change taxonomy disabling method

linkerd.io/config.toml, linkerd.io/layouts/index.redirects
This PR adds the basic Hugo scaffolding necessary to auto-generate a Netlify `_redirects` file. There is not yet a need for redirects, but this will become necessary in the near future (see #163).
=> Add auto-generated redirects file

linkerd.io/layouts/partials/cli/flags.html
The **Default** column is no longer used for CLI flags, so it should be removed from the template.
=> Remove default field from flags table

linkerd.io/layouts/partials/footer.html
This PR adds a nice-looking button to the footer to replace the "edit this site" logic currently in place. On the home page it links to the root of the repo. On specific pages it takes you straight to the "edit" page on GitHub for that specific page.
=> Add edit page/site button

linkerd.io/content/2/reference/cli/check.md, linkerd.io/content/2/tasks/troubleshooting.md
linkerd/linkerd2#2361 renamed the second
`can query the control plane API` check to
`control plane self-check`.
This is the corresponding documentation change.
=> Update linkerd check reference with self-check

linkerd.io/content/2/tasks/troubleshooting.md
Follow-up to https://github.com/linkerd/linkerd2/pull/2358: Update website "troubleshooting" section to have information about new kubectl check.
Signed-off-by: Yan Babitski [yan.babitski@gmail.com](yan.babitski@gmail.com)
=> Update troubleshooting with kubectl-version check

linkerd.io/content/2/getting-started/_index.md
I didn't realize when reviewing #207 that we're now using a link checker that requires trailing slashes on internal links. That change fails `make check`, with:
```
htmltest started at 10:59:15 on public
========================================================================
2/getting-started/index.html
target is a directory, href lacks trailing slash --- 2/getting-started/index.html --> /2/tasks/automating-injection
========================================================================
✘✘✘ failed in 2m55.29255331s
1 errors in 319 documents
```
This update fixes it and should fix the [CI failure](https://circleci.com/gh/linkerd/website/53). Maybe we should be running the link checker on non-master branches, too?
=> Fix link linting on getting started page

linkerd.io/content/1/overview/_index.md, linkerd.io/layouts/1/overview.html, linkerd.io/layouts/_default/baseof.html, linkerd.io/layouts/partials/docs.html, linkerd.io/layouts/partials/footer.html, linkerd.io/layouts/partials/javascript.html
In attempting to implement a fix for #201 I had trouble grokking JavaScript imports, the logic for which is sprinkled across several places. This PR centralizes all JS logic into a single partial and leans on conditionals for page- and section-specific importing. This should make it easier to do JavaScript-y things in the future.
=> Combine JS logic into one partial

run.linkerd.io/public/emojivoto-daemonset.yml, run.linkerd.io/public/emojivoto.yml
Though emojivoto doesn't currently _need_ service accounts for any good
reason, they enhance the identity demo.
All services now have dedicated accounts except the vote-bot, which continues
to use the "default" account.
=> emojivoto: Add service accounts

linkerd.io/content/dashboard/20190313.md, linkerd.io/content/dashboard/entry1.md, linkerd.io/content/dashboard/entry2.md, linkerd.io/content/dashboard/entry3.md
This branch adds our first official community updates page, announcing the updates page itself. This will be displayed in the linkerd web UI once linkerd/linkerd2#2476 ships. As part of this changed, I switched to date-based filenames for updates.
=> Replace placeholder updates with first community update

linkerd.io/assets/scss/custom.scss, linkerd.io/assets/scss/index.scss, linkerd.io/layouts/partials/breadcrumb.html, linkerd.io/layouts/partials/docs.html
Addresses issue #223. The implementation isn't super elegant but it works.
**Important caveat**: If the documentation "tree" goes any deeper than it currently does, the breadcrumb will not work. Make sure to adjust for additional levels should the need arise.
You can see an example implementation here:
https://deploy-preview-224--linkerd.netlify.com/2/reference/cli/completion/
=> Add breadcrumb implementation for docs

Makefile
This PR updates the version of the edge release to edge-19.3.3.
=> Updating edge version to edge-19.3.3

linkerd.io/static/upgrade/index.html
This PR adds a redirect that will send `linkerd.io/upgrade/#anchor` to `linkerd.io/2/tasks/upgrade/#anchor`. 
The `linkerd.io/upgrade` pattern is currently being used by `linkerd upgrade` in the CLI.
=> Adding redirect for linkerd.io/upgrade

linkerd.io/content/2/tasks/troubleshooting.md
- Add a section for `has NET_ADMIN capability`
- Fix hint anchor for `is running the minimum kubectl version`
- Standardize section headers at level 2, checks at level 3
Fixes #254
=> Update checks troubleshooting page for 2.3

linkerd.io/content/2/features/cni.md
`--linkerd-cni-enabled` is no longer used at `inject` time. Update docs
to reflect this.
Fixes #270
=> Update CNI docs to reflect config-based install

linkerd.io/content/2/tasks/using-ingress.md
This adds instructions on how to use the Gloo API Gateway (https://github.com/solo-io/gloo) in conjunction with Linkerd.
Signed-off-by: Diogenes Rettori <rettori@gmail.com>
=> Gloo as ingress

linkerd.io/content/2/tasks/troubleshooting.md
This change documents checks added via the `linkerd check config`
command.
Depends on linkerd/linkerd2#2765
=> Add troubleshooting sections for multi-stage check

linkerd.io/content/2/tasks/configuring-retries.md
Tweak the wording and snippet for configuring retryable routes. The old wording suggested that only requests with bodies were retryable, and didn't actually show the field in the associated snippet.
=> Fix documentation for isRetryable

linkerd.io/content/2/tasks/troubleshooting.md
Subject
New hint anchor reflecting new pre-install check
Problem
There is a pending PR for new healthcheck. In order for this healthcheck to be fully implemented, an update is also required for the troubleshooting page.
Solution
Updated the relevant page with anchor and a paragraph with hint
References [issue 2762 ](https://github.com/linkerd/linkerd2/issues/2762) in the `linkerd2` repository
Signed-off-by: Matej Gera <matejgera@gmail.com>
=> New hint anchor reflecting new pre-install check

linkerd.io/content/2/tasks/troubleshooting.md
#297 introduced trailing whitespace that broke the `make lint` check. I'm not sure why that wasn't detected on the branch and only appeared once the change made it to master. This should fix it.
=> Fix whitespace linting issue

linkerd.io/content/2/tasks/using-ingress.md
Subject
Small typo on [using-ingress](https://linkerd.io/2/tasks/using-ingress/) page
Problem
The text reads "terminal HTTPS" and it should read "terminate HTTPS"
Solution
Fix the typo
Validation
Just eyeballed it.
Fixes #303
=> 303: fix ingress note typo

linkerd.io/content/2/getting-started/_index.md
As stated in #311, minimum K8s version seems to be 1.10 instead of 1.9. This is a just a bump of this requirement on the website :slightly_smiling_face:
=> Bump minimum Kubernetes cluster version from 1.9 to 1.10 (Closes #311)

linkerd.io/content/2/tasks/uninstall.md
Running
`linkerd install | kubectl delete -f -`
will only output 
`Linkerd has already been installed on your cluster in the linkerd namespace. Please run upgrade if you'd like to update this installation. Otherwise, use the --ignore-cluster flag.`
Running `linkerd install --ignore-cluster | kubectl delete -f -` seems to do the job.
=> Fix uninstall.md

linkerd.io/content/dashboard/20190531.md
Updates the community dashboard page to include a Linkerd2 stable-2.3.1 announcement.
=> update community page for 2.3.1 release.

linkerd.io/content/2/tasks/exporting-metrics.md
I wanted to use a ServiceMonitor to configure my Federation Scraping. So i put one together and tested it. I thought it might help others to add that to the docs.
=> Add ServiceMonitor setup example

linkerd.io/content/1/_index.md, linkerd.io/content/2/_index.md, linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-iii-encrypting-all-the-things.md, linkerd.io/package-lock.json, linkerd.io/package.json
Subject: Upgrade vulnerable dependency
Problem: js-yaml, a dependency of markdown-lint-cli has a security vulnerability
Solution: Upgrade markdown-lint-cli in package.json to 0.14.1 to upgrade js-yaml to 3.13.1
Fixes: #333
=> Upgrade vulnerable sub-dependency: js-yaml

linkerd.io/content/2/reference/cli/inject.md
Remove references to -f
```
Error: unknown shorthand flag: 'f' in -f
Usage:
linkerd inject [flags] CONFIG-FILE
```
=> inject -f is not supported

linkerd.io/layouts/partials/homepage/top-hero.html
Adds `&rel=0` flag to end of embedded YouTube link so that the videos suggested at the end are from Buoyant's channel.
*NOTE* when building a preview locally with `hugo serve` the YouTube video did not autoplay on `master` or my branch. Since autoplay is working on `linkerd.io` I think this is a consequence of running a preview but would like a second opinion from someone who worked on the redesign.
Before:
After:
=> Make embedded YouTube video recommend Buoyant content

linkerd.io/themes/buoyant/assets/bulma/sass/grid/columns.sass
An attempt at fixing issue #355 
Before (1080p):
After (1080p):
=> Prevented the tweets from overflowing off the page

linkerd.io/layouts/page/dashboard.html, linkerd.io/layouts/partials/css.html, linkerd.io/static/css/dashboard-updates.css
This PR styles the dashboard update page at `linkerd.io/dashboard`. The styling had changed with the redesign.
Before:
After:
=> Restoring CSS styling for dashboard update page

linkerd.io/content/2/getting-started/_index.md, linkerd.io/content/2/tasks/install.md, linkerd.io/content/2/tasks/uninstall.md, linkerd.io/content/2/tasks/upgrade.md
Add a multi-stage section to `/tasks/install`, link to it from Getting
Started page.
Fixes #380
=> Add docs for multi stage installation

linkerd.io/content/2/reference/cli/check.md, linkerd.io/content/2/reference/cli/install.md, linkerd.io/content/2/reference/cli/upgrade.md, linkerd.io/data/cli.yaml, linkerd.io/layouts/partials/cli/annotations.html, linkerd.io/layouts/shortcodes/cli.html, linkerd.io/layouts/shortcodes/cli/examples.html, linkerd.io/layouts/shortcodes/cli/flags.html
Modified CLI reference rendering code to not display subcommands on
index page, and instead reference them in their respective parent
command pages.
Add new annotations:
- `config.linkerd.io/disable-identity`
- `config.linkerd.io/disable-tap`
- `config.linkerd.io/enable-debug-sidecar`
- `config.linkerd.io/init-image-version`
Depends on https://github.com/linkerd/linkerd2/pull/3016
Depends on #387
Fixes #381
=> Update the CLI and annotation docs for 2.4

linkerd.io/content/2/tasks/troubleshooting.md
=> 2.4 - Bump the supported k8s version to 1.12

linkerd.io/content/2/tasks/upgrade.md
Tested the following scenarios with stable-2.3 and stable-2.3.2:
```sh
`kubectl get all,sa,cm,secret,role,rolebinding,clusterrole,clusterrolebinding,mutatingwebhookconfiguration,validatingwebhookconfiguration,crd,psp --all-namespaces -l linkerd.io/control-plane-ns=linkerd -L linkerd.io/control-plane-ns`
```
Fixes #349.
=> 2.4 - Upgrade notes

linkerd.io/content/2/getting-started/_index.md, linkerd.io/content/2/reference/architecture.md, linkerd.io/content/2/tasks/install.md, linkerd.io/content/2/tasks/upgrade.md, linkerd.io/content/2/tasks/using-debug-endpoints.md, linkerd.io/content/2/tasks/using-psp.md, linkerd.io/content/2/tasks/using-the-debug-container.md
Fixing a few things that I spotted when reviewing the docs that were added in #403. New docs look great, btw!
=> Fix a few typos in recently added docs

linkerd.io/layouts/partials/main-menu.html
If you navigate to the [Get Started](https://linkerd.io/2/getting-started/), the `is-active` class makes the Get Started button a little funky because it applies the same underline style to *all* menu components. This PR changes the `is-active` logic to not apply to the button.
The relevant page is here: https://5d3f39e4abf08f00080e4bf1--linkerd.netlify.com/2/getting-started/
=> Fix navbar CSS issue

linkerd.io/content/2/tasks/securing-your-cluster.md, linkerd.io/static/tap-rbac/index.html
Also add a redirect from `linkerd.io/tap-rbac`, to reference in Tap
APIServer RBAC error messages.
Relates to https://github.com/linkerd/linkerd2/issues/3191
=> Introduce a Securing Your Cluster page, tap

run.linkerd.io/public/install, run.linkerd.io/public/install-edge
If the install scripts rely on awk, they malfunction when run on a
device with a limited environment where awk is not available. This patch
replaces the use of awk with cut, which is expected to be more
ubiquitous than awk (and as a bonus also more lightweight on footprint,
execution time and command line length).
Change-Id: I035bf20cb891402677d0a8fbd49ca6fcd099341d
Signed-off-by: Joakim Roubert <joakimr@axis.com>
=> Use cut instead of awk in the install scripts

run.linkerd.io/public/install, run.linkerd.io/public/install-edge
It seems sha256sum is more ubiquitous than openssl which would suggest
using it in the install scripts make them more portable. Also using
shell script built-in functionality to trim the sha256sum output which
eliminates the depdency towards awk.
Change-Id: I2e6ceed6ffbb406bc440d5f7d2f816d1f23b4f85
Signed-off-by: Joakim Roubert <joakimr@axis.com>
=> Use sha256sum instead of openssl in the install scripts

linkerd.io/layouts/partials/meta.html
Having these ancient search results crop up as at the top of searches like
"linkerd grpc" is producing all sorts of confusing content for 2.x users.
Keep the content around, just don't let it be returned in search results.
=> stop indexing 1.x content

linkerd.io/content/1/getting-started/_index.md, linkerd.io/content/2/getting-started/_index.md
=> make /getting-started go to 2.x docs, not 1.x docs

run.linkerd.io/public/install, run.linkerd.io/public/install-edge
Add check not only if to use Darwin or Linux, but also make sure not to
install the Linux amd64 binaries on e.g. a Linux armv7l system. Then a
proper (?) error message will be displayed and the script aborts.
When/if more systems are supported, they are easily added with this
structure.
Change-Id: Ia0b23785cb89a6620fcbba27aff8270bcf4008ff
Signed-off-by: Joakim Roubert <joakimr@axis.com>
=> Make install script(s) fail on unsupported systems

linkerd.io/content/2/features/ha.md
The current HA documentation is outdated with respect to anti-affinity rules for critical pods as of 2.5.0 stable release.
Document the impact of https://github.com/linkerd/linkerd2/pull/2893 on anti-affinity rules for control plane pods.
Related to https://github.com/linkerd/website/issues/400
=> Update state of pod anti-affinity rules in HA mode

linkerd.io/content/2/tasks/upgrade.md
Add the options `--prune -l linkerd.io/control-plane-ns=linkerd` to
`kubectl` after the `linkerd upgrade` commands.
Also added an explanatory paragraph.
=> Clarifying notes for `linkerd upgrade`

linkerd.io/content/2/features/ha.md
Adds documentation (per linkerd/linkerd2#3346) for proxy injector mutating webhook "skip webhook" label on `kube-system` in `--ha` mode as implemented in linkerd/linkerd2#3460
=> ha mwc: add label to kube-system

linkerd.io/content/_index.md
Hello - I'm responsible for certain elements of the Cisco Webex platform, the choice to use linkerd therein, and generally a big fan . . . however, the way the Cisco Webex product name/logo are currently displayed on the linkerd.io home page could be easily interpreted as a deliberate endorsement by Cisco of linkerd, rather than just an external observation that we are in fact using the linkerd software. Unfortunately, I've been unable to find evidence that any request was made to Cisco for permission to reference the Cisco Webex name/logo in this way.
Unless I'm mistaken, and some formal interaction with Cisco has occurred re. use of the Cisco Webex name/logo in this manner, please remove the reference either by merging this PR, or any other means.
=> Remove Cisco Webex endorsement

run.linkerd.io/public/flagger.yml
Due to missing deployment selector apply fail with 'missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec'
Adding selector solve the issue.
Fixes #533
Signed-off-by: Mario Vejlupek mario@vejlupek.cz
=> Add missing selector to flagger.yml

linkerd.io/content/blog/bringing-service-communication-shadows-part-2.md, linkerd.io/data/cli.yaml, linkerd.io/layouts/partials/cli/annotations.html
This PR updated to docs to include new 2.6 CLI and annotations.
The dead link error shown by `lint` is fixed in https://github.com/linkerd/website/pull/537.
Fixes https://github.com/linkerd/linkerd2/issues/3468.
=> Include 2.6 CLI Options and Annotations

linkerd.io/content/2/tasks/using-custom-domain.md
This PR adds documentation on how to use the `--cluster-domain` option introduced in https://github.com/linkerd/linkerd2/pull/3360.
Fixes https://github.com/linkerd/website/issues/530.
=> Documentation on how to use custom domain

run.linkerd.io/public/install, run.linkerd.io/public/install-edge
If openssl is missing on the system, the install script(s) will try to
use shasum instead.
Change-Id: Ifb453d497bc5f8e2c9db4f4438ed178390b3db99
Signed-off-by: Joakim Roubert <joakimr@axis.com>
=> Add shasum as fallback SHA256 sum provider

linkerd.io/content/2/tasks/install-helm.md, linkerd.io/content/2/tasks/upgrade.md
This PR includes the 2.6 upgrade notes. I also re-organize the upgrade docs to re-use common sections like _upgrading the cli_, _upgrading the control plane_ and _upgrading the data plane_, so that we won't have to repeat those commands in subsequent upgrade notes.
I specifically call out the data plane downtime, due to the migration of the `destination` container into its own workload. We can discuss in-person to see if there are ways around it.
=> 2.6 upgrade notes

linkerd.io/content/2/tasks/upgrade.md, run.linkerd.io/public/install, run.linkerd.io/public/install-edge
- Add an `INSTALLROOT` var to the install script, defaulting to `${HOME}/.linkerd2`
- Save the downloaded binary into `${INSTALLROOT}/bin/linkerd-${LINKERD2_VERSION}`
- If the same version is already present and the checksum passes, do not redownload
- Symlink `${INSTALLROOT}/bin/linkerd` to the versioned binary
- Fail the script if the curl commands fail
- Update documentation to note the presence of versioned binaries
=> Allow installing parallel linkerd versions and custom install dirs.

linkerd.io/content/2/tasks/upgrade.md, run.linkerd.io/public/install, run.linkerd.io/public/install-edge
A change to the install script caused failures in some shell
environments:
```bash
$ cat run.linkerd.io/public/install | sh
sh: 8: Syntax error: "(" unexpected
```
Revert the change until a fix can be found.
=> Revert #501

linkerd.io/content/2/tasks/using-ingress.md
Documenting the `nginx.ingress.kubernetes.io/upstream-vhost` annotation with a static value for now.
We'll need to explore the correct way to dynamically set this value. the `$` nginx variables are not available to the annotation based on the testing that I've done. Will have to dig in to where this is added in the nginx configuration
=> Document the nginx.ingress.kubernetes.io/upstream-vhost annotation

linkerd.io/content/2/tasks/install-helm.md
This PR adds `--name=linkerd2` to the Helm install procedure docs so Helm release name is `linkerd2`. Also adds forward slashes to HA installation code so it can be copied as-is.
=> Add --name flag to Helm docs for Helm install procedure

linkerd.io/content/2/tasks/upgrade.md
This PR updates the `--from-manifests` portion of the upgrade docs, by removing the first example where the whole output of the `linkerd install` command is written to a manifest file. As filed in https://github.com/linkerd/linkerd2/issues/3559, this approach is now causing the `linkerd upgrade` command to fail due to the `k8s.FakeClientSet` not being able to deserialize the `APIService` kind. Since the original intent of this option (see https://github.com/linkerd/linkerd2/issues/2629) is to read the `linkerd-config` config map, I think it's fair to remove the failing example in the docs.
Fixes https://github.com/linkerd/linkerd2/issues/3559.
=> Update 'from-manifest' upgrade docs

linkerd.io/content/2/features/ha.md
These commands were missing the `-` that's necessary to apply a manifest from stdin.
=> Fix commands in the ha docs

Makefile
Of course that fails now as there is still no edge-19.11.3
Signed-off-by: zaharidichev <zaharidichev@gmail.com>
=> Update Makefile edge version to edge-19.11.3

linkerd.io/content/2/getting-started/_index.md
Fixes #591
The existing instructions in the "Getting Started" section of the documentation cover the install script and downloading the CLI binary manually. However for users with Homebrew it may be easier to install the CLI this way.
This change adds alternative instructions to install the Linkerd CLI using Homebrew to "Step 1" of the "Getting Started" documentation.
=> Add install instructions using Homebrew

linkerd.io/content/2/tasks/generate-certificates.md
the `identity-issuance-lifetime` flag configures how long service certificates that the identity service issues are valid.  It does not configure the lifetime of the issuer certificate itself.  I don't believe there is any reason here to recommend a longer issuance lifetime than the default of 24h.
=> Don't set issuance lifetime

linkerd.io/layouts/page/dashboard.html
From `Linkerd2 Dashboard`, we need to know the body height of this template to render it properly into an iframe injected on `Community` section.
We post a message with the body height from `dashboard` template using `postMessage` method to its parent. This height is going to be used by `Linkerd2 Dashboard` to render properly the iframe, which contains these community updates.
Related to [#3764](https://github.com/linkerd/linkerd2/issues/3764)
Signed-off-by: Cintia Sanchez Garcia <cynthiasg@icloud.com>
=> Post message with body height from dashboard template 

README.md
If `make deploy-api.linkerd.io` fails, then you may need to follow the instructions in the note.
We can also look into updating the dependencies, but I worry about breaking backward compatibility.
=> Add a note about setting the SDKROOT

linkerd.io/content/2/reference/cli/dashboard.md, linkerd.io/content/2/tasks/exposing-dashboard.md, linkerd.io/data/cli.yaml, linkerd.io/layouts/shortcodes/pagetoc.html, linkerd.io/static/dns-rebinding/index.html
Fixes #571
@grampelberg what's the best way to create a redirect from https://linkerd.io/dns-rebinding to https://linkerd.io/2/tasks/exposing-dashboard/#tweaking-host-requirement ? Like with healthchecks, create a new page `dns-rebinding` and have javascript in there do the redirect?
=> Added DNS rebinding docs

linkerd.io/content/2/tasks/using-a-private-docker-repository.md
This is a draft at the docs for using a private repo for air-gapped environments.
I'd like to be able to dynamically fill in the latest stable and edge release versions. Are there variables for that?
Also looking for a way to expand on the CI/CD portion by dynamically setting the image names using helm charts or other options.
=> #587 add private repo info

linkerd.io/content/2/tasks/exposing-dashboard.md, linkerd.io/content/2/tasks/setting-up-service-profiles.md
Right now the `pagetoc` on these two pages is rendering incorrectly due to a Hugo syntax error:
* https://linkerd.io/2/tasks/setting-up-service-profiles
* https://linkerd.io/2/tasks/exposing-dashboard
This PR fixes that with a small syntax change.
=> Fix pagetoc shortcode problem

linkerd.io/content/2/getting-started/_index.md
Changed 
```
The `linkerd inject` command adds annotations to the pod spec
instructing Linkerd to add ("inject") the data plane's proxy is added as a
container to the pod spec. (See [Automatic Proxy
Inject](/2/features/proxy-injection/) for more.)
```
with
```
The `linkerd inject` command adds annotations to the pod spec
instructing Linkerd to add ("inject") the proxy as a container to the pod spec.
(See [Automatic Proxy Injection](/2/features/proxy-injection/) for more.)
```
=> Tiny phrase fix in the getting started page

linkerd.io/content/2/tasks/canary-release.md
- `kubectl rollout status` doesn't require the `--wait` flag
- Added missing `frontend` item in the service list
=> Small updates to canary-release.md

linkerd.io/content/2/tasks/install-helm.md
Turns out we cannot simply upgrade the helm chart in case of breaking changes to it. There are bit more details that ned to be considered. Therefore I expanded on the docs a bit to keep the users informed. Currently ` helm upgrade linkerd2 linkerd/linkerd2 --reuse-values` when moving from 2.6 to edge does not work. 
=> Elaborate on helm upgrade

linkerd.io/content/2/tasks/replacing_expired_certificates.md, linkerd.io/content/2/tasks/rotating_identity_certificates.md
- Usually after linkerd commands we show the pipe to kubectl, but that's missing in the linkerd upgrade command under "Replacing the root and issuer certificates"
- In that same doc, there's no instructions on rolling out the dataplane pods so they pick the new cert.
- In "Rotating your Identity Certificates" section "Generate new trust root and issuer certificates" it doesn't mention that all of this is for rotating certs without downtime.
Ref linkerd/linkerd2#3898
=> Minor improvements to the cert rotation docs

linkerd.io/content/2/tasks/install-helm.md
globals.noInitContainer is now globals.cniEnabled
This is to be merged after linkerd/linkerd2#3956 merges
=> Update Helm install doc with renamed value

linkerd.io/content/2/tasks/distributed-tracing.md
- `kubectl rollout status` doesn't require the `--watch` flag
- Clarify one has to click on "Find Traces" (this got me!)
- Should be `ingress-nginx` instead of `nginx-ingress`
=> Small updates to distributed-tracing.md

.gitignore, linkerd.io/content/2/tasks/books.md, linkerd.io/layouts/partials/meta.html
- Clarified the wording around the tap screen. Also spell out `tap` instead of just using the icon, because it doesn't render everywhere (it didn't in my Chrome under Linux).
- Updated `linkerd lap` output
- Updated `linkerd routes` output , where a dash is used now instead of zeroes when an item doesn't have traffic
Other changes:
- Added `bin` to .gitignore (where the platform-specific `htmltest` is placed)
- Removed utf8 meta tag from `meta.html` given it's already declared in `head.html` and so it's being shown twice.
=> Various minor doc improvements mainly in books.md

linkerd.io/layouts/partials/meta.html
Per https://ogp.me/, we should be setting `og:url` to
> The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".
Currently we set it to `https://linkerd.io` for everything, which breaks sharing on LinkedIn.
This patch changes it to what I *believe* is the actual canonical URL for the page.
=> fix canonical og urls

linkerd.io/content/2/tasks/using-the-debug-container.md
=> add quotes to annotation so k8s doesn't break on copy and paste

linkerd.io/content/2/tasks/canary-release.md
This PR updates the canary release task to Flagger v1.0.0 (Canary CRD v1beta1).
Signed-off-by: stefanprodan <stefan.prodan@gmail.com>
=> Update canary docs to Flagger v1.0

linkerd.io/content/2/tasks/install-helm.md
In helm chart for v2.7.0 variable names changed from ```Namespace``` to ```namespace``` and ```InstallNamespace``` to ```installNamespace```
=> Fix variable names to proper one

linkerd.io/content/2/tasks/automatically-rotating-control-plane-tls-credentials.md
After a bit of reading, seems using cert manager + vault is the sensible way to do automatie cert rotation. I think explaining that + pointing to the docs + explaining what are the requirements to achieve auto cert rotation by our identitiy service makes sense.
=> Elaborate on using Vault + third party solutions

linkerd.io/content/blog/linkerd-distributed-tracing.md
Subject
fix typo in distributed tracing blog post
Problem
just a simple typo. someone uses "of" instead of "or"
Solution
~of~ or
Fixes
N/A - no issue filed
Signed-off-by: Lucas Melchior <switchboard.op@gmail.com>
=> Fix typo in distributed tracing blog post

linkerd.io/content/2/tasks/exposing-dashboard.md
Followup to linkerd/linkerd2#4054
Add some detail into the Tweaking Host Requirement section to include
new available Helm variable for the host enforcement requirement.
=> Add instructions for using enforcedHostRegexp

linkerd.io/content/2/tasks/generate-certificates.md
Signed-off-by: alex lundberg <alex.lundberg@commonbond.co>
=> update helm install docs to use linkerd/ instead of charts/ as the base

linkerd.io/content/2/tasks/automatically-rotating-control-plane-tls-credentials.md, linkerd.io/content/2/tasks/generate-certificates.md
It is in some cases desirable to have a longer than default lived trust anchor certificate for long lived clusters.
Also added headers to distinguish between Trust anchor creation and Issuer Cert/Key creation.
=> Describe how to achieve longer lived trust anchor certificates.

linkerd.io/content/2/tasks/troubleshooting.md
Looks like it was cargoculted from the `linkerd` namespace.
=> Fix example of kube-system namespace

linkerd.io/content/2/tasks/upgrade.md
@grampelberg, per our conversation I ran these upgrade tests:
- 2.4.0 to 2.6.0
- 2.5.0 to 2.6.0
In both cases, the 2.4.0 and 2.5.0 proxies running under the 2.6.0 control plane continued to run without error.
I also confirmed that a pod injected with a 2.4.0 proxy could successfully communicate with a pod injected with a 2.6.0 proxy.
I'll run the same tests with 2.6.1, and for now, the tests support the documentation.
=> Clarify data-plane restart requirements

linkerd.io/content/2/tasks/using-ingress.md
The Kubernetes service `web-svc` listens to port 80. So this definition needs to be changed. It is already port 80 in the other Ingress definitions. Also I checked the "Getting Started" emojivote Kubernetes deployment.
=> Fix port for web-svc

linkerd.io/layouts/partials/cli/annotations.html
Image depicting issue (Chrome):
Image depicting layout after fix (Chrome):
Allow annotation to wrap, preventing description from clipping on longer annotations. Also makes the page more readable at half-width.
Signed-off-by: Theodore Brockman <tbrockma@ualberta.ca>
=> proxy-configuration page description clipping fix

linkerd.io/content/2/features/multicluster.md
For some reason Google search results point to this 404 URL when searching
for "linkerd multicluster". Have it redirect to the real URL.
=> add redirect to features/multicluster_support

linkerd.io/content/community.md
DevOps role has been removed from Kaskada.com
=> Removing Kaskada because the page is no longer available

linkerd.io/content/2/features/traffic-split.md
The link to the smi-spec was broken, it was moved in the upstream repo.
This was tested by running the site locally and checking the link was valid and to the expected page.
Fixes #755 
Signed-off-by: Alistair Hey <alistair.hey@form3.tech>
=> Fix link to smi-spec traffic-split

run.linkerd.io/public/emojivoto-daemonset.yml, run.linkerd.io/public/emojivoto-statefulset.yml, run.linkerd.io/public/emojivoto.yml
The SMI `TrafficSplit` resouce makes it easy to configure canary releases
in Linkerd. It relies on a `Service` that resolves to all versions
of an application and each version having their own `Service` that
resolves to only endpoints for that version.
Since the current `Deployment` manifests at https://run.linkerd.io/emojivoto.yml
only include the `app` label, you have to redeploy the service you want
to demo `TrafficSplit` with with a `version` label in order to get it
to work properly.
Adding a `version` label will make it so we do not have to redeploy the
current version.
See: https://github.com/BuoyantIO/emojivoto/pull/90
Signed-off-by: Noah Krause <krausenoah@gmail.com>
=> Add version label to ease SMI TrafficSplit config

linkerd.io/content/2/tasks/distributed-tracing.md, linkerd.io/data/cli.yaml
Under the NGINX ingress section of the distributed tracing task, there is a reference indicating to use a service as a trace collector that will not exist after a traditional Linkerd2 installation (the same reference is copied to the CLI documentation).
Slack message giving context here: https://linkerd.slack.com/archives/C89RTCWJF/p1596584278173200
Signed-off-by: Theodore Brockman <tbrockma@ualberta.ca>
=> Fix two trace-collector references in documentation

linkerd.io/content/2/tasks/external-prometheus.md
* API endpoint for prometheus is generally under / and not under /api/prom ( this endpoint is for writing back to prometheus)
* when using external prometheus the sample frequency needs to be higher than for example what is the default in prometheus helm chart 
* Using the already deployed prometheus configuration is a good starting point as a reference for an external prometheus setup.
=> fixing external prometheus setup documentation

run.linkerd.io/public/install, run.linkerd.io/public/install-edge
Followup to #785
When we move the downloaded binary to its final location, we first try
with the file using the architecture suffix, and if that doesn't work we
fallback to not use that suffix. That works, but if the first try fails
we're showing an ugly error:
```
$ curl -sL https://run.linkerd.io/install-edge|sh
...
Download complete!
Validating checksum...
Checksum valid.
mv: cannot stat '/tmp/linkerd2.qY5SfJ/linkerd2-cli-edge-20.7.5-linux-amd64': No such
file or directory
Linkerd edge-20.7.5 was successfully installed 🎉
Add the linkerd CLI to your path with:
export PATH=$PATH:/home/alpeb/.linkerd2/bin
Now run:
linkerd check --pre                     # validate that Linkerd can
be installed
linkerd install | kubectl apply -f -    # install the control
plane into the 'linkerd' namespace …
```
=> l5d install script: Mute error when attempting to move unexisting file

run.linkerd.io/public/install-edge
@cpretzer @alpeb 
As the [edge](https://github.com/linkerd/linkerd2/releases/tag/edge-20.8.1) release now already support multi-arch.
These fallback scripts are not necessary anymore, therefore we remove it.
We will do the same for the `install` script when the stable release is published.
=> Remove fallback script for install-edge

linkerd.io/content/2/tasks/automatically-rotating-control-plane-tls-credentials.md
Running linkerd versions <= stable-2.8.1 with cert-manager version 0.15
experimental controllers enabled causes linkerd-identity pods to crash
with this error message:
> "Failed to initialize identity service: failed to read CA from disk: unsupported block type: 'PRIVATE KEY'"
This commit documents some potential solutions to this problem.
Signed-off-by: Peijun Ma <peijun.ma@protonmail.com>
=> Document cert-manager experimental controller issue

linkerd.io/content/2/tasks/manually-rotating-control-plane-tls-credentials.md
Update the trust anchor rotation doc to include steps to restart application proxies after the new issuer is deployed.
Fixes https://github.com/linkerd/linkerd2/issues/4287
=> Add steps to restart application proxies

linkerd.io/content/2/tasks/exposing-dashboard.md
Hey Maintainers,
I have added an example to expose the dashboard via [Ambassador](https://www.getambassador.io/) Ingress. I stumbled on this [issue](https://github.com/linkerd/linkerd2/issues/4929) and thought of documenting this.
Thanks,
Vikas
=> Added an example to expose dashboard via Ambassador Ingress

linkerd.io/content/2/features/traffic-split.md
Updating the broken link for SMI's traffic split API. 
Signed-off-by: Cizer Pereira <mail@cizer.dev>
=> Update broken link for SMI traffic split api

linkerd.io/content/2/tasks/using-ingress.md
Depends on BuoyantIO/emojivoto#96 so that we can set the `HOST_OVERRIDE` environment variable.
Depends on #840 for the `--ingress` explanation link to work.
Context: linkerd/linkerd2#5160
=> Add changes for setting up Kong ingress

multicluster/base/frontend.yml, multicluster/base/patch.yml
All containers are able to run as non-root. Therefore it's okay add the `securityContext` to the Kubernetes deployments.
<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> run multicluster example website as nonroot

linkerd.io/content/2/tasks/automatically-rotating-control-plane-tls-credentials.md, linkerd.io/content/2/tasks/automatically-rotating-webhook-tls-credentials.md
Problem: Examples use older v1alpha3 syntax which has changed slightly in v1
Solution: Update examples to use cert-manager v1 which was released 4 months ago.
Fixes #881 
Signed-off-by: Keith Burdis <keith.burdis@gs.com>
=> Update examples to use cert-manager v1

linkerd.io/content/2/tasks/automatically-rotating-control-plane-tls-credentials.md, linkerd.io/content/2/tasks/automatically-rotating-webhook-tls-credentials.md, linkerd.io/content/2/tasks/generate-certificates.md, linkerd.io/content/2/tasks/gitops.md, linkerd.io/content/2/tasks/installing-multicluster.md, linkerd.io/content/2/tasks/manually-rotating-control-plane-tls-credentials.md, linkerd.io/content/2/tasks/multicluster.md
Problem: The subject of the linkerd-trust-anchor CA certificate in 'Automatically Rotating Control Plane TLS Credentials' and 'Multi-cluster communication' is currently identity.linkerd.cluster.local which is the same as intermediate CA certificate linkerd-identity-issuer and I found this confusing.
Solution:  The subject/issuer of the trust anchor CA should be changed to reflect its purpose.
Fixes: #883
Signed-off-by: Keith Burdis <keith.burdis@gs.com>
=> Set subject of the linkerd-trust-anchor CA certificate to reflect its purpose

run.linkerd.io/public/emojivoto-daemonset.yml, run.linkerd.io/public/emojivoto-statefulset.yml, run.linkerd.io/public/emojivoto.yml
I've setup scarf.sh to front our emojivoto images. This change updates
emojivoto's dmeo kubernetes manifests to refer to the new custom repo
location.
=> emojivoto: Update docker repo to docker.l5d.io

linkerd.io/.htmltest.yml
https://conduit.io is no longer serving linkerd related content and the htmltest link checks are failing.
Addiing conduit.io to the list of excluded domains is a temporary fix until I can clean up all the conduit.io links.
=> Add conduit.io to excluded htmltest domains

linkerd.io/content/blog/under-the-hood-of-linkerd-s-state-of-the-art-rust-proxy-linkerd2-proxy.md
A link appears to have been permanently removed, so I replaced it with one from Google Scholar
=> Update link in proxy blog

linkerd.io/themes/buoyant/layouts/partials/schema.html
The FAQ fields in the linked JSON (`<script type="application/ld+json">`) schema had non-compliant JSON, so this change uses hugo's `htmlEscape` to render the characters in a JSON compliant format
=> htmlEscape the FAQ text fields for the linked JSON schema

linkerd.io/content/2/tasks/upgrade.md
Due to a known issue in versions stable-2.9.0, stable-2.9.1, and stable-2.9.2,
users who upgraded to one of those versions with the --prune flag (as described
above) will have deleted the `secret/linkerd-config-overrides` resource which is
necessary for performing any subsequent upgrades. Linkerd stable-2.9.3 includes
a new `linkerd repair` command which restores this deleted resource. If you see
unexpected error messages during upgrade such as "failed to read CA: not
PEM-encoded", please upgrade your CLI to stable-2.9.3 and run:
```bash
linkerd repair | kubectl apply -f -
```
This will restore the `secret/linkerd-config-overrides` resource and allow you
to proceed with upgrading your control plane.
=> 2.9.3 upgrade notes

linkerd.io/content/2/tasks/manually-rotating-control-plane-tls-credentials.md
=> Fix typo of yq arguments ("Manually Rotating Control Plane TLS Credentials" page)

linkerd.io/content/2/tasks/troubleshooting.md, linkerd.io/data/cli.yaml
The `logs` command was removed in linkerd/linkerd2#5203.
=> Remove references to logs command

linkerd.io/.htmltest.yml
External link checks are extremely flaky.
=> Disable CheckExternal link checking

linkerd.io/content/2/features/dashboard.md, linkerd.io/content/2/tasks/adding-your-service.md, linkerd.io/content/2/tasks/books.md, linkerd.io/content/2/tasks/canary-release.md, linkerd.io/content/2/tasks/exporting-metrics.md, linkerd.io/content/2/tasks/exposing-dashboard.md, linkerd.io/content/2/tasks/fault-injection.md, linkerd.io/content/2/tasks/getting-per-route-metrics.md, linkerd.io/content/2/tasks/securing-your-cluster.md, linkerd.io/content/2/tasks/securing-your-service.md, linkerd.io/content/2/tasks/setting-up-service-profiles.md
Put `viz` in the CLI commands that were moved to the Viz extension, and add instructions on how to install Viz there where required. Also use Helm configs there where the flags are no longer supported, and updated then viz namespace in some resource yamls .
I didn't do a thorough follow-up on the instructions for each doc that was updated, so I'm not yet marking them as completed in #5867
=> [2.10] Update CLI commands that were moved to Viz

linkerd.io/content/2/tasks/extensions.md
Linkerd extensions are components which can be added to a Linkerd
installation to enable addition functionality.  By default, the following
extensions are available:
* Linkerd-viz: Metrics and visibility features
* Linkerd-jaeger: Distributed tracing
* Linkerd-multicluster: Cross-cluster routing
A Linkerd extension is made up of two parts: a CLI whose name must begin with
`linkerd-` and a set of Kubernetes resources created by that CLI.  Every
extension must create a Kubernetes namespace with the `linkerd.io/extension`
label.  You can list all extensions installed on your cluster by running:
```bash
kubectl get ns -l linkerd.io/extension
```
Before installing any extensions, make sure that you have already
[installed Linkerd](/2/tasks/install/).  Validate your install by running:
```bash …
```
=> Add extensions page

linkerd.io/content/2/tasks/exporting-metrics.md
This PR updates the `Exporting Metrics` doc to reflect the changes
that happened with 2.10
=> [2.10] update exporting metrics docs

linkerd.io/content/2.10/tasks/upgrade.md, linkerd.io/content/blog/announcing-linkerd-2-10.md, linkerd.io/layouts/partials/docs.html
- update blog post to point to 2.10 specific resources. /2/ points to the wrong thing.
- denote non-current versions of the docs
- use relative links in blog post for debugging
- add `linkerd repair` instructions for 2.10 upgrades
- add 2.9.4 pseudo-instructions
=> more 2.10 upgrade doc tweaks

.github/dependabot.yml, .github/workflows/check.yml, .github/workflows/validate.yml
This fixes some issues with the SEO Check:
- added TOML support
- added support for `+++` delims
- fixed fail status
Also adds a dependabot config for automated version updates on GitHub Actions.
=> fix: separate seo check with pr_target trigger, add dependabot config

linkerd.io/content/2.10/getting-started/_index.md
this do not work:
```bash
linkerd -n linkerd viz top deploy/linkerd-web
```
this works:
```bash
linkerd -n linkerd-viz viz top deploy/web
```
=> fix top demo

linkerd.io/content/2.10/reference/cli/diagnostics.md, linkerd.io/content/2.10/reference/cli/endpoints.md, linkerd.io/content/2.10/reference/cli/viz.md
Add aliases to the `diagnostics` and `viz` CLI reference pages to
account for the subcommands that were moved and are now housed under
there.  Also deletes the `endpoints.md` file whose info was also moved
under `diagnostics`.
=> Add aliases for moved subcommands

.github/workflows/check.yml
updated the action to only comment on PRs when relevant files were modified.
=> chore: bump seo action to be less chatty on PRs

linkerd.io/layouts/partials/faqs.html
=> fix(faq): anchor links break with special characters in questions

.github/workflows/check.yml
sorry, there was another issue with the action, it's fixed now. No more empty SEO messages from the bot.
=> fix: no empty seo messages in PRs

run.linkerd.io/public/install-edge
With the addition of linkerd/linkerd2#5907, users with the new MacOS M1
arch need to be able to easily install the CLI. This change modifies the
edge bash script to detect the new arch and install the correct image.
=> Update the edge install script to download M1 CLI

bin/export-channel-versions
Currently the site is showing the latest stable to be 2.9.5 because
that's the latest stable version by date in github. Correcting to 2.10.1
manually, till we fix this properly. Note this affects the result
retrieved in https://run.linkerd.io/install
=> Temporary stable version fix

linkerd.io/content/2.10/features/ha.md, linkerd.io/content/2.10/tasks/installing-multicluster.md, linkerd.io/content/2.10/tasks/using-ingress.md, linkerd.io/content/2.10/tasks/using-the-debug-container.md, linkerd.io/content/2.9/features/ha.md, linkerd.io/content/2.9/tasks/installing-multicluster.md, linkerd.io/content/2.9/tasks/using-ingress.md, linkerd.io/content/2.9/tasks/using-the-debug-container.md
Some links under the `2.9` and `2.10` directories were malformed: `https://linkerd.io../../<url>`
This change updates those links to be relative links: `../../<url>`
=> Fix broken links

linkerd.io/content/2.10/getting-started/_index.md
The getting started page does not currently mention that the Control Plane TLS credentials will ultimately expire, leading to nasty surprises a year down the line.
Adding links to the relevant documentation on the getting started page should fix this.
Fixes https://github.com/linkerd/linkerd2/issues/6099
=> add tls rotation to getting started suggestions

linkerd.io/content/2.10/tasks/automatically-rotating-webhook-tls-credentials.md
This PR updates the code snippet in the guide on how to configure automatic rotation of webhook TLS credentials to use the `--values` flag instead of the `--config` flag, which is no longer available.
Signed-off-by: Emanuel Winblad <winblad@me.com>
=> Auto-rotating Webhook TLS Credentials: Changed the --config flag in code snippet to be --values instead

linkerd.io/layouts/partials/meta.html, linkerd.io/themes/buoyant/layouts/partials/twitter-cards.html
Closes https://github.com/BuoyantIO/website/issues/241
**Home page card**
**Blog card example**
=> Twitter cards show large image summary for blog posts

linkerd.io/content/2.10/getting-started/_index.md
Seems to be the only place in the docs where a plain HTTP link remains. It seems quite important to have HTTPS since the command is downloading a bash script and piping it to bash.
=> Add HTTPS to linkerd CLI install instructions

linkerd.io/content/2.10/tasks/canary-release.md
People (and I) were trying to test things by port-forwarding `podinfo`,
but that directs you straight into the primary pod, skipping the
trafficsplit logic. Towards the end of the page there were proper
instructions to use the frontend service instead, but it's clearer if we
do that from the beginning.
This was clarified after this convo with a user:
https://linkerd.slack.com/archives/C89RTCWJF/p1622732904469200
=> Clarify Canary Release Tutorial

linkerd.io/content/_index.md
The HP/Webex/Clover Health logos do not link to the respective company websites
This commit addresses this in the source material for the static site generation tool
Fixes #1103
Signed-off-by: Gavin Chappell <44392051+gchappell99@users.noreply.github.com>
=> Update 3 homepage links to match the logos (#1103)

linkerd.io/content/2.10/reference/proxy-configuration.md
Overrriding the proxy configuration using the command line flag has been possible for some time.
Update the proxy configuration page to reference that.
Signed-off-by: Krzysztof Drys <krzysztofdrys@gmail.com>
=> Reference inject flags in proxy configuration page

linkerd.io/content/2.10/tasks/using-ingress.md
Fixes linkerd/linkerd2#6237
- Since a few releases ago, `linkerd inject` will fail outright if
`automountServiceAccountToken` is not `true`. Reshuffled the instructions to
account for that.
- Added note about adding the
`config.linkerd.io/skip-outbound-ports: 8001` annotation when in ingress mode.
- Removed the `spec.routes.services.namespace` field from the sample
`HTTPProxy` resource, which doesn't appear in the resource API doc.
- Replaced `127.0.0.1.xip.io` with `127.0.0.1.nip.io` as the former is down.
=> Update Contour instructions

linkerd.io/content/2.10/tasks/exposing-dashboard.md, linkerd.io/content/2.10/tasks/using-ingress.md
Ref linkerd/linkerd2#6508
Ingress version `extensions/v1beta1` will disappear in k8s 1.22, so
this upgrades it to `networking.k8s.io/v1` alongside with other required
Ingress changes.
=> Upgrade Ingress resources

linkerd.io/content/2.10/tasks/gitops.md, linkerd.io/content/2.9/tasks/gitops.md
Typo in documentation. Should be `global` instead of `gloval`.
=> docs: typo gloval to global

linkerd.io/layouts/extensions/list.json.json
This change fixes an issue where the screenshot link for the
extensions/index.json endpoint would contain a double forward slash.
This was caused by the `list.json.json` adding a forward slash
regardless of whether the base URL did or did not already contain a
forward slash. This change now premptively strips a forward slash from
the base URL if it exists and then formats the screenshot URL correctly.
=> Fix double forward slash issue in extensions json

.github/workflows/check.yml, linkerd.io/content/2.10/tasks/using-ingress.md, linkerd.io/content/2.9/tasks/using-ingress.md
Fixes #1030 
* Added documentation describing the `nginx.ingress.kubernetes.io/service-upstream` annotation
* Added section advising users to review available configuration for their ingress controller before recommending `Proxy Ingress Mode`
* Cleaned up Kong formatting
=> Improve ingress docs

.github/workflows/check.yml
there were some breaking changes in @actions/github that I missed. `pull_request` should suffice here.
=> chore: update markdown check

linkerd.io/content/2.10/tasks/automatically-rotating-control-plane-tls-credentials.md
Fixes linkerd/linkerd2#6561
This adds some extra instructions on how to manually generate a secret
with the issuer credentials when not using cert-manager.
=> Instructions for setting up cert secret

.github/workflows/check.yml
* Update check.yml action to use [markdown-seo-check](https://github.com/zentered/markdown-seo-check) v1.1.2
=> Rollback to markdown seo v1.1.2

linkerd.io/content/2.10/tasks/_index.md, linkerd.io/content/2.10/tasks/exposing-dashboard.md, linkerd.io/content/2.10/tasks/securing-your-cluster.md, linkerd.io/static/next-steps/index.html, run.linkerd.io/public/install, run.linkerd.io/public/install-edge
The stable and edge install scripts were referencing a broken link:
https://linkerd.io/2.10/next-steps
Modify the scripts to instead reference:
https://linkerd.io/2/tasks
Also, introduce a redirect from `/next-steps` to `/tasks`.
=> Fix broken links in install scripts, add redirect

linkerd.io/layouts/partials/meta.html, linkerd.io/themes/buoyant/layouts/_default/baseof.html, linkerd.io/themes/buoyant/layouts/partials/head.html
- Removed Universal Analytics tag `UA-60040560-2`
- Replaced Google Tag Manager tag `GTM-KHF5SSN` with `GTM-PXBDGKJ` which
is solely for linkerd.io and is not shared with buoyant.io. Also note
this new tag will add the tag `UA-60040560-2` automatically.
=> Marketing tags cleanup

linkerd.io/content/2.10/tasks/troubleshooting.md
With BuoyantIO/linkerd-buoyant#31, the `linkerd-buoyant check` command
now provides a hint URL pointing to
https://linkerd.io/checks#l5d-buoyant.
Update the troubleshooting docs to include resolution steps in case of
`linkerd-buoyant check` failures.
Relates to BuoyantIO/linkerd-buoyant#31
=> Add a `linkerd-buoyant` section to troubleshooting

linkerd.io/content/support-training.md, linkerd.io/layouts/partials/enterprise/support.html
* Add Buoyant training course signup to training & support page.
* Remove Kubernetes course. Not sure why that would be on a Linkerd page.
* target=_blank for external links
=> add Buoyant training offering

linkerd.io/content/2.10/tasks/exposing-dashboard.md
Fixes linkerd/linkerd2#6969
Using an empty string for `enforceHostRegexp` doesn't disable that
check; it just falls back to the default of checking against the default
`^(localhost|127\.0\.0\.1|web.linkerd-viz.svc.cluster.local|web.linkerd-viz.svc|\[::1\])(:\d+)?$`.
So we just fix the docs saying if you wanna disable this check , just
use a catch-all regex `.*`.
=> Fix doc about disabling dashboard host header check

run.linkerd.io/public/emojivoto-policy.yml
This PR adds a new file under `run.linkerd.io` to have a
`emojivoto` policy manifest, that is maintained and updated
based on the changes from `emojivoto.yml` manifest here.
This will make it possible to access the policy manifest from
`run.linkerd.io/emojivoto-policy.yml`
=> add emojivoto policy manifest

run.linkerd.io/public/emojivoto-policy.yml
The example emojivoto policy was intially written to exercise a variety
of policy functionality, but isn't actually how we'd write policies for
emojivoto. Furthermore, because it uses an identity glob, it cannot work
in clusters with custom domains.
In order to make the example more representative of how policy would
actually be applied, this change unifies the emoji and voting
authorizations to a single authorization, `internal-grpc`, that selects
both the voting and emoji server by selector.
=> Simplify emojivoto policy example

run.linkerd.io/public/install, run.linkerd.io/public/install-edge
The program shasum generates output in the following
format: `hash filename` and current scripts was
considering the filename as the hash.
Changed the regex to strip the filename and keep the hash.
Fixes linkerd/linkerd2#7202
=> Correct checksum on installation

linkerd.io/content/2.11/features/cni.md, linkerd.io/content/2.11/tasks/install-helm.md
The `helm search` command is deprecated in favor of `helm search repo`.
=> Fix Helm example commands

linkerd.io/config.toml, linkerd.io/content/2.11/reference/iptables.md, linkerd.io/content/2.11/tasks/distributed-tracing.md, linkerd.io/content/2.11/tasks/multicluster-using-statefulsets.md, linkerd.io/content/_index.md, linkerd.io/content/design-principles/_index.md, linkerd.io/content/gsoc.md, linkerd.io/content/what-is-a-service-mesh/_index.md, linkerd.io/layouts/partials/docs.html, linkerd.io/layouts/shortcodes/latest-linkerd2-stable-version.html
- Added new site param `latest_linkerd2_stable_version`
- Used that in `layouts/partials/docs.html` instead of having to hard-code the version
- Created shortcode `latest-linkerd2-stable-version` using that setting
- Used shortcode in `design-principles/_index.md` and `tasks/distributed-tracing.md` instead of hard-coded version
- Removed hard-coded version in `gsoc.html` and instead take advantage of alias url
- Replaced versioned url with relative url in `reference/iptables.md`
=> A few versioning improvements before branching off the 2.12 docs

linkerd.io/content/2.10/tasks/using-ingress.md, linkerd.io/content/2.11/tasks/using-ingress.md
Currently the shown example of a Ingress resource with the service-upstream
annotation is invalid in that the annotations value is a boolean where only
string values are allowed.
This change updates the example to be valid.
Signed-off-by: Crevil <bjoern.soerensen@gmail.com>
=> Set nginx service-upstream annotation as string

linkerd.io/content/2.12/features/cni.md, linkerd.io/content/2.12/tasks/automatically-rotating-control-plane-tls-credentials.md, linkerd.io/content/2.12/tasks/automatically-rotating-webhook-tls-credentials.md, linkerd.io/content/2.12/tasks/generate-certificates.md, linkerd.io/content/2.12/tasks/installing-multicluster.md, linkerd.io/content/2.12/tasks/manually-rotating-control-plane-tls-credentials.md
Followup to #1245, updating all the helm commands in various docs, catering for the new `linkerd-base` and `linkerd-control-plane` charts. Also got rid of old helm v2 references.
=> Update helm commands

linkerd.io/content/2.10/tasks/distributed-tracing.md, linkerd.io/content/2.11/tasks/distributed-tracing.md, linkerd.io/data/cli.yaml
Replace linkerd-collector.linkerd to collector.linkerd-jaeger
Fixes #1249
Signed-off-by: FingerLiu <liupeng.dalian@gmail.com>
=> Fix service name of trace collector in docs

linkerd.io/content/2.11/tasks/multicluster.md, multicluster/base/frontend.yml, multicluster/base/kustomization.yml, multicluster/base/patch.yml
Fixes linkerd/linkerd2#7504
Kustomize breaking changes and other upgrades made that tutorial obsolete. Fixed with:
- Removed namespaces from resources and patch, and instead use `kubectl -n test apply`
- Having vars in the nginx' location targets implies declaring a dns resolver. Also extended FQDN for services is required.
- The nginx container requires running as root to allow using apk to install cURL
Also improved the tutorial itself:
- Added instructions for installing viz
- Removed not-required line-feeds in `echo` statements
- http://localhost:8080/east requires cURL and doesn't work in the browser because of javascript reasons
- Added missing directives in cleanup steps
=> Fix multicluster tutorial and kustomize resources

linkerd.io/content/blog/linkerd-service-account-tokens.md
The wrong volumeMount was used in the example. This
PR fixes that to use the right one.
=> blog: fix volumeMount in tokens blog post

linkerd.io/content/2.12/tasks/gitops.md
It now takes into account the upcoming change in linkerd 2.12.0 where we
replace the `linkerd2` helm chart with the `linkerd-crds` and
`linkerd-control-plane` charts.
Other updates:
- Added instructions to install the ArgoCD CLI
- Updated ArgoCD version and point to location for the latest stable
manifest
- Update ArgoCD password retrieval mechanism
- Added instructions to install the `kubeseal` CLI utility
The `linkerd/linkerd-examples` repo this tutorial uses has also been updated in linkerd/linkerd-examples#267
=> Update ArgoCD tutorial

linkerd.io/content/2.12/tasks/install-helm.md, linkerd.io/content/2.12/tasks/upgrade.md
This updates the helm install instructions to account for the new charts
as per linkerd/linkerd2#6635
Also this adds a new section for 2.12 in `upgrade.md`, detailing the
migration steps needed for the new charts.
=> Helm migration instructions for 2.12

linkerd.io/content/2.11/reference/architecture.md
Was reading architecture and noticed a typo in the markdown link to K8s admission controller docs.
=> Fix admission controller link in architecture.md

linkerd.io/content/2.9/tasks/installing-multicluster.md
Closes linkerd/linkerd2#7612.
The gateway port is `4143`, not `4183`.
=> Fix port to proxy's inbound port

linkerd.io/content/2.10/tasks/using-ingress.md, linkerd.io/content/2.11/tasks/using-ingress.md
Update docs to let users know `ServiceProfile` resources and sticky sessions are mutually exclusive. 
=> Update ingress docs with mention of session stickiness

linkerd.io/content/2.11/tasks/grafana.md
Fixes linkerd/linkerd2#7745
Copied `grafana.md` doc from #1244 from the 2.12 docs into 2.11, for
folks that are on edge releases, that already have stripped-off the
Grafana instance.
=> External Grafana doc

linkerd.io/layouts/shortcodes/cli/annotations.html
Fixes #1297
The proxy reference page instead of showing the annotations list was
showing the list of commands.
=> Fix cli/annotations shortcode

linkerd.io/content/2.11/tasks/canary-release.md
It's not obvious in the docs that we need to install the Linkerd SMI-extension before following this tutorial. This PR adds that prereq.
=> Update canary-release.md: add prereq of SMI-extension

linkerd.io/content/2.10/tasks/installing-multicluster.md, linkerd.io/content/2.11/tasks/installing-multicluster.md, linkerd.io/content/2.9/tasks/installing-multicluster.md
We've had a number of users get confused by the Ambassador instructions in the
multi-cluster docs. This change removes these instructions.
Signed-off-by: Oliver Gould <ver@buoyant.io>
=> Remove Ambassador instructions from multi-cluster doc

linkerd.io/content/2.11/tasks/extensions.md
Add more info about installing the Buoyant Cloud extension, now that auto-cluster registration is supported.
This replaces #1324.
=> Update getting started guide for Buoyant Cloud extension

linkerd.io/content/2.11/tasks/troubleshooting.md
Signed-off-by: Håkon Solbjørg <hakon@solbj.org>
I'm not sure where to put the anchor because the linter complained about the line being too long if it was put on the same line as  the header.
=> docs: Add troubleshooting section for proxy-init-run-as-root

linkerd.io/content/2.11/features/multicluster.md
Makes it easier to understand.
=> Remove mentions of 'source' and 'target' cluster in headless docs

.devcontainer/devcontainer.json, Dockerfile
In order to have a more reproducible dev environment for the website, we update the website-builder docker image to make it suitable for use as a devcontainer.
Once merged, we will update the BUILD_IMAGE version of website-builder from 1.3.3 to 1.4.0, and publish it as 1.4.0 and have CI use this new version.  This will ensure consistency between dev and CI.
=> Add a devcontainer

.github/workflows/publish.yml, linkerd.io/build
The publish step seems to fail when trying to build the website. Inside the build script, a `CURRENT_SHA` env variable is set to the latest git commit sha. When building the website, however, the contents are moved to a temp directory that does not appear to be a git repository. Because of this, attempting to do `git rev-parse` to set the value of `CURRENT_SHA` fails.
This change removes the unused `CURRENT_SHA` variable to allow the site to be built.
The `CURRENT_SHA` variable appears to be unused
=> Add env variable to publish workflow

.github/workflows/publish.yml, linkerd.io/content/2.11/tasks/manually-rotating-control-plane-tls-credentials.md, linkerd.io/content/blog/under-the-hood-of-linkerd-s-state-of-the-art-rust-proxy-linkerd2-proxy.md
References to deleted tweets seem to break the website build, this change removes a reference that seems to affect the build script.
=> Remove deleted tweet

Makefile, api.linkerd.io/build, linkerd.io/build
The `make shellcheck` task checks the install scripts but does not check other
scripts in this repo. This change updates it to check all scripts.
Signed-off-by: Oliver Gould <ver@buoyant.io>
=> Run shellcheck on all bash scripts

linkerd.io/content/2.10/tasks/troubleshooting.md, linkerd.io/content/2.11/tasks/troubleshooting.md
As of `stable-2.10.0`, Linkerd's control plane no longer ships with the
controller and sp-validator pods. Our `linkerd check` troubleshooting
guide still includes the two pods in the guide. This change removes any
mention of `linkerd-controller` and `linkerd-sp-validator`. Where
applicable, mentions of `linkerd-controller` have been replaced with
`linkerd-identity` to exemplify any check warnings or errors.
=> Remove mentions of linkerd-controller

linkerd.io/content/2.10/features/protocol-detection.md, linkerd.io/content/2.11/features/protocol-detection.md
NetworkPolicies that restrict ingress access should target the proxy's
inbound port (4143) when the application's exposed port is marked as
opaque. The outbound proxy will re-write the target port based on the
opaque protocol hint set by the destination controller.
=> Add NetworkPolicy notes to protocol detection

linkerd.io/content/2.11/features/traffic-split.md
The [documentation for Traffic Split](https://linkerd.io/2.11/features/traffic-split/) does not link to the step-by-step instructions on the [Linkerd SMI](https://linkerd.io/2.11/tasks/linkerd-smi/#) page. This PR adds the missing link.
Signed-off-by: Jeremy Chase <jeremy.chase@gmail.com>
=> Link from Traffic Split to SMI task page

linkerd.io/content/2.11/tasks/manually-rotating-control-plane-tls-credentials.md, linkerd.io/content/2.11/tasks/replacing_expired_certificates.md
We need to document needing to restart Linkerd to pick up changes.
=> Update the trust anchor rotation documentation

linkerd.io/content/2.12/tasks/upgrade.md
Markdownlint [suggests][1] that bash snippets showing commands to be run
only include a `$` prefix before the command when the snippet also
includes output from that command. This is why the CI build for the
`alpeb/2.12` branch [is currently failing][2]. 
To fix CI, this branch disables that rule (MD014) in `tasks/upgrade.md`.
As far as I can tell, Markdownlint doesn't support some kind of config
file or other way to disable a rule for the whole repo...
[1]: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md014---dollar-signs-used-before-commands-without-showing-output
[2]: https://github.com/linkerd/website/runs/7911493490?check_suite_focus=true
=> upgrade: remove `$` from bash snippets without output

linkerd.io/content/2.12/tasks/troubleshooting.md
This check is run as part of `linkerd viz check --proxy`, _not_ 
`linkerd check --proxy`, but it's currently in the section "The
'linkerd-data-plane' checks". I've moved it to the section "The
'linkerd-viz' checks, which I think is where it should be.
=> move data plane proxy metrics check to `linkerd-viz` section

linkerd.io/content/2.12/tasks/customize-install.md, linkerd.io/content/2.12/tasks/troubleshooting.md, linkerd.io/content/2.12/tasks/upgrade.md
Clean up some whitespace and be consistent about H2 & H3 in the upgrade notices.
- Fix whitespace lint issues
- Be consistent about H2/H3 in the upgrade notes.
=> Fix markdown linting

linkerd.io/content/2.12/tasks/using-ingress.md
This is a cherry-pick of @alpeb's ingress-mode warning, onto the new `shared/docs/2.12`, since @alpeb is out at the moment. (Retargeting his #1398 to `shared/docs/2.12` did not have good results. 😂)
@alpeb's comments below:
> Note that, as explained below, some ingress options need to be meshed in
"ingress" mode, which means injecting with the `linkerd.io/inject: ingress`
annotation rather than the default `enabled`. It's possible to use this
annotation at the namespace level, but it's recommended to do it at the
individual workload level instead. The reason is that many ingress
implementations also place other types of workloads under the same namespace for
tasks other than routing and therefore you'd rather inject them using the
default `enabled` mode (or some you wouldn't want to …
=> Alejandro's ingress-mode warning

linkerd.io/content/2.12/features/server-policy.md
Once the per-route policy guide is written, the Example section at the bottom should be replaced with a pointer to that.
=> update authorization policy feature doc for 2.12

linkerd.io/content/2.12/reference/authorization-policy.md
Added reference documentation for policy resources
* HTTPRoute
* AuthorizationPolicy
* MeshTLSAuthentication
* NetworkAuthentication
Fixes #1432
=> Update authorization policy resource reference

linkerd.io/content/2.12/tasks/configuring-per-route-policy.md
This branch updates the HTTPRoute authorization tutorial added in #1426
so that the names of policy resources are links to the corresponding
reference docs for those resource types.
This is a separate draft PR because these links will be broken until PR
#1428, which actually adds the reference docs for the policy resource
types, is merged. This PR will either merge into #1426 if #1428 merges
first, or into `shared/docs/2.12` if #1426 merges before #1428.
=> tasks: linkify resource names in authz tutorial

linkerd.io/content/2.12/tasks/customize-install.md, linkerd.io/content/2.12/tasks/troubleshooting.md
Update the hint anchors to match the current set of possible check failures in the linkerd 2.12 CLI.  Remove hints for errors which are no longer generated and add hints that were missing.
=> Update troubleshooting hint anchors

linkerd.io/content/2.12/features/nft.md, linkerd.io/content/2.12/reference/architecture.md
Since the introduction of 'nft' mode, linkerd-init can be run in different
modes. This PR adds a feature page to detail how the two modes differ, and how
config can be overridden. Additionally, we mention the two modes in the
architecture page.
Closes #1411
=> Add feature page for iptables modes

linkerd.io/content/2.12/getting-started/_index.md
This branch makes the following changes to the "Getting Started" docs:
- Adds the `linkerd install --crds` command prior to `linkerd install`.
- Removes the mention of multi-stage install, which no longer exists.
- Adds a link to the authorization policy docs in the section on next
steps.
=> update "Getting Started" docs

linkerd.io/content/2.12/tasks/configuring-per-route-policy.md
apparently that's a totally separate scope for markdown link references?
who knew!
=> fix broken links in route policy docs note

linkerd.io/content/2.12/tasks/using-debug-endpoints.md
Fixes #1459 
Indicate that the `enablePprof` must be set to enable this.
=> update pprof tutorial

linkerd.io/content/2.12/tasks/securing-linkerd-tap.md
Fixes #1458 
Also reword the opening paragraph to better contextualize the content.
=> Rename "Securing Your Cluster" to "Securing Linkerd Tap"

linkerd.io/content/2.12/tasks/automatically-rotating-control-plane-tls-credentials.md
Fixed #1491, since the `linkerd-base` chart doesn't exist.
=> Fix documentation on auto-rotating TLS with Helm

.devcontainer/on-create.sh
markdownlint is needed in order to run `make lint` 
=> Add markdownlint to on-create script

linkerd.io/content/2.12/tasks/install-helm.md
As of 2.12.0, when installing via Helm, helm itself should create the namespace (or some other step in the CD pipeline), and we no longer require any special metadata on it.
=> Remove obsolete instructions for namespace customization

linkerd.io/content/2.12/tasks/troubleshooting.md
https://github.com/linkerd/linkerd2/pull/9567 added a check to ensure that all ClusterIP services have IP addresses in the cluster network.  This new check uses `#l5d-cluster-networks-pods` as the hint anchor, just like the existing check for ensuring that pods are in the cluster networks.  
We update the text of this hint to discuss both pods and ClusterIP services.
=> Update cluster network hint

linkerd.io/content/2.12/features/automatic-mtls.md
Document the TLS version and cipher suite used for mTLS connections, as this information may be required for security audit purposes in some deployment environments.
=> Document TLS version and cipher suite used for mTLS connections

linkerd.io/content/2.12/reference/authorization-policy.md, linkerd.io/content/2.12/tasks/generate-certificates.md
Am fixing some issues that I found in the Authorization Policy doc, as follows:
- For `HTTPRouteMatch`, both the `headers` and `queryParams` fields use list values rather than object values
- For `HTTPRequestRedirect`, the field for the status code should be `statusCode` instead of `status`
- For the `type` field on multiple objects, the "RegularExpression" type was misspelled
Signed-off-by: Kevin Ingelman <ki@buoyant.io>
=> Correctness updates for Authorization Policy reference

linkerd.io/content/2.12/reference/proxy-metrics.md
Currently, the documentation for proxy metrics states that the `status_code`, `grpc_status_code`, and `classification` labels are present on "all `response_*` metrics". This is incorrect. The `response_latency_ms` metric does not include `classification` and `grpc_status_code` labels, since it is recorded when the first byte of a response body is received, and the response is not classified (and the gRPC status is not known) until the response body _ends_. The incorrect docs have caused confusion for users (see linkerd/linkerd2#9737).
This branch updates the proxy metrics documentation to distinguish between the labels that are present on all `response_*` metrics, and the labels that are present only on `response_total` metrics. In addition, I added a note explaining _why_ some labels are …
=> docs: only response total metrics have classifications

linkerd.io/content/2.12/tasks/external-prometheus.md
Fixes https://github.com/linkerd/linkerd2/issues/9660
Add a note indicating that prometheus scrape interval must be shorter than query time duration and add example.
=> Add note about prometheus scrape interval

linkerd.io/content/2.12/tasks/distributed-tracing.md
Fixes https://github.com/linkerd/linkerd2/issues/9753
Our emojivoto based reference architecture does not use an ingress, but instead uses vote-bot to initiate traces.  However, the docs still make reference to using nginx as an ingress for this.
Update the docs to indicate that an ingress typically initiates traces but that our reference architecture uses vote-bot instead.
=> Remove ingress from tracing docs

run.linkerd.io/public/install
The stable `install` script had fallen behind the `install-edge` script.
Update `install` to match `install-edge`, specifically:
- add `linkerd install --crds` command example
- remove `linkerd dashboard` command example
- add a `linkerd viz` section
- handle Mac M1 arch
=> Update CLI install script to match install-edge

linkerd.io/content/2-edge/tasks/install-helm.md, linkerd.io/content/2.12/tasks/install-helm.md
The `helm install` commands with `values-ha.yaml` were not setting the `-n linkerd` flag, causing linkerd to be installed into the `default` namespace.
Modify the `helm install` examples to set `-n linkerd`.
=> Set `-n linkerd` in helm HA install examples

linkerd.io/static/uploads/sma-2023/2023-05.ics
This should've been 18 May 12-1330. Fixed now.
=> Whoops, it's 18 May.

linkerd.io/content/2-edge/reference/proxy-metrics.md
This branch adds documentation for the new metrics added in linkerd/linkerd2-proxy#2377 and linkerd/linkerd2-proxy#2380.
=> document outbound route metrics

linkerd.io/content/2-edge/reference/authorization-policy.md, linkerd.io/content/2-edge/reference/httproute.md
Moved out of Authorization Policy given it's also used for Header-Based routing which is unrelated to Auth.
Also added missing fields in the ref.
Upcoming: Header-Based routing tutorial
=> Moved HTTPRoute reference doc into its own page

linkerd.io/content/2-edge/tasks/automatically-rotating-control-plane-tls-credentials.md, linkerd.io/content/2.13/tasks/automatically-rotating-control-plane-tls-credentials.md
Was fixed in 2.12 here https://github.com/linkerd/website/pull/1581 but not in 2.13 / edge.
=> fix typo which in auto rotate control plane tls

linkerd.io/content/2-edge/tasks/configuring-proxy-discovery-cache.md
Documents the new helm values
- `proxy.outboundDiscoveryCacheUnusedTimeout`
- `proxy.inboundDiscoveryCacheUnusedTimeout`
and their associated annotations:
- `config.linkerd.io/proxy-outbound-discovery-cache-unused-timeout`
- `config.linkerd.io/proxy-inbound-discovery-cache-unused-timeout`
Currently added only to the `2-edge` docs. Will add to `2.13` when/if it gets cherry-picked into a dot release.
=> Document discovery cache configuration options

linkerd.io/content/blog/2023/0621-edge-roundup.md
It makes me tremendously sad that this doesn't look right on the website, but it passed lint _and_ rendered correctly in my local preview. 😢 
=> Apparently a double slash in an image URL passes website lint but doesn't render correctly?? Also fix the alt text. Sigh.

linkerd.io/content/2-edge/features/httproute.md, linkerd.io/content/2-edge/reference/httproute.md, linkerd.io/content/2-edge/tasks/configuring-timeouts.md
This branch adds new documentation for the HTTPRoute timeout fields
added in Linkerd 2.14. This includes adding the HTTPRoute timeout fields
to the HTTPRoute reference docs, and adding a section on using HTTPRoute
timeouts to the "Configuring Timeouts" tasks doc.
=> document HTTPRoute timeouts

linkerd.io/content/2-edge/features/retries-and-timeouts.md
The Features/Retries and Timeouts documentation currently only mentions that retries and timeouts can be configured using ServiceProfiles. This branch updates it to also refer to HTTPRoutes and link to those docs as well.
=> mention HTTPRoute in "Retries and Timeouts" doc

linkerd.io/content/2-edge/reference/httproute.md
Support for the ResponseHeaderModifier HTTPRoute filter was added in
2.14. This branch updates the HTTPRoute docs to reflect that this filter
is availble.
=> add ResponseHeaderModifier to HTTPRoute docs

linkerd.io/content/2-edge/features/httproute.md, linkerd.io/content/2-edge/features/retries-and-timeouts.md, linkerd.io/content/2-edge/reference/authorization-policy.md, linkerd.io/content/2-edge/reference/httproute.md, linkerd.io/content/2-edge/tasks/configuring-dynamic-request-routing.md, linkerd.io/content/2-edge/tasks/configuring-per-route-policy.md, linkerd.io/content/2-edge/tasks/configuring-timeouts.md, linkerd.io/content/2-edge/tasks/fault-injection.md
As of Linkerd 2.14, we now support HTTPRoutes with both the `policy.linkerd.io` and `gateway.networking.k8s.io` API groups. This branch adds documentation discussing the differences between these two API groups, and notes in the docs stating that both are supported.
=> document Linkerd and Gateway HTTPRoute API groups

linkerd.io/content/2-edge/tasks/using-ingress.md
PM from ngrok here. We have recently released an open source ngrok ingress controller and would love to add it as an option in your guide. 
I was able to run through the getting started guide with linkerd using a local k3d cluster. After completing that guide, i was able to install the ngrok ingress controller into it's own namespace and apply the included ingress.yaml example with no issues. 
I'm not quite sure about the meshing mode needed here. I applied the [example command](https://linkerd.io/2.14/tasks/adding-your-service/#examples) to the ngrok-ingress namespace and didn't have any issues with the emojivoto app, and the linkerd viz dashboard seems to think everything is meshed and working 🤷🏼
=> feat: add ngrok ingress controller to ingress guide in docs

linkerd.io/layouts/partials/case-studies.html, linkerd.io/layouts/partials/homepage/companies.html
Linked buoyant logo in the company list, and opened cased studies in a new tab.
=> Fixed links on home page

linkerd.io/content/2-edge/getting-started/_index.md, linkerd.io/content/2.10/getting-started/_index.md, linkerd.io/content/2.11/getting-started/_index.md, linkerd.io/content/2.12/getting-started/_index.md, linkerd.io/content/2.13/getting-started/_index.md, linkerd.io/content/2.14/getting-started/_index.md, linkerd.io/content/2.9/getting-started/_index.md
Let's keep it simple and point them to content we already have on the site.
=> remove references to production toolkit

linkerd.io/content/blog/linkerd-hero-march.md, linkerd.io/content/community/heroes/_index.md, linkerd.io/layouts/community/heroes.html, linkerd.io/layouts/partials/heroes/heroes-section.html
We are currently missing a content header on the Heroes page. We have 2 sections: voted and nominated, and they run together without anything separating them. Since we haven't added nominated heroes since 2021, we should remove them.
For voted heroes, instead of linking to their Github or Linkedin page, we should link to the blog, if it available.
---
With this PR, I have removed the nominated heros, and updated the links to point to the blog post for voted heroes. If a blog post wasn't made for a hero, then the existing Github or Linkedin url is used.
I also checked to see if every hero blog post had a link to the hero's Github or Linkedin page, and added it if needed. The one exception is the blog post for Dom DePasquale. The Github page we have for him returns a 404, and I can't find …
=> Removed nominated heroes, linked to blog for voted heroes

linkerd.io/content/2.14/getting-started/_index.md
More details: https://github.com/linkerd/website/pull/1703
The installation instructions provided in [Step 1](https://linkerd.io/2.14/getting-started/#step-1-install-the-cli) of the Linkerd documentation could benefit from additional clarity. Specifically, the documentation should include a step to add the Linkerd CLI to the system's PATH for easy access.
That's what I did.
=> [DOCS] Path for linkerd cli

linkerd.io/content/2.14/getting-started/_index.md, linkerd.io/content/2.14/reference/k8s-versions.md, linkerd.io/content/2.14/tasks/install.md, linkerd.io/content/2.14/tasks/upgrade.md
Fixes [#11474](https://github.com/linkerd/linkerd2/issues/11474)
=> Add supported-versions doc

linkerd.io/content/2.14/reference/k8s-versions.md
=> Added table styles to supported Kubernetes versions

linkerd.io/content/2-edge/tasks/configuring-retries.md, linkerd.io/content/2.11/tasks/configuring-retries.md, linkerd.io/content/2.12/tasks/configuring-retries.md, linkerd.io/content/2.13/tasks/configuring-retries.md, linkerd.io/content/2.14/tasks/configuring-retries.md
=> Update retry docs.

.gitignore, Makefile, bin/generate_release_matrix.py, linkerd.io/content/releases/_index.md, linkerd.io/content/releases/release_matrix.json, linkerd.io/content/releases/release_matrix.yaml, linkerd.io/data/releases/release_matrix.json, linkerd.io/layouts/shortcodes/release-data-table.html
Previously, there was not an easy way to correlate the app version to a helm chart version.  Many people ask this question in public slack channel or must get data themselves.  This adds a script to produce the desired matrix data as a table, json, or yaml output to help folks who are upgrading.  Without this matrix the versions are very confusing.  A python script is provided to generate the necessary data. 
This also adds a new make target to produce the content `build-release-matrix`.  I prepended the target call to the `build-linkerd.io` target so that upon creation the data would be generated.
=> Adds helm chart to app version matrix

linkerd.io/content/2.14/getting-started/_index.md
In the getting-started `_index.md` there was a typo which I noticed and fixed.
=> Fix getting-started index.md typo

linkerd.io/content/2.15/getting-started/_index.md
Move to use `-edge` as the current script gives this warning.
```
*******************************************
* This script is deprecated and no longer *
* installs stable releases.               *
*                                         *
* The latest edge release has been        *
* installed. In the future, please use    *
*   run.linkerd.io/install-edge           *
* for this behavior.                      *
*                                         *
* For stable releases, please see         *
*  https://linkerd.io/releases/           *
*******************************************
```
=> 2.15 and forward getting-started docs should point people to edge CLI

linkerd.io/content/2.15/tasks/adding-non-kubernetes-workloads.md
This PR fixes a typo that can cause users to experience problems when their non k8s proxies are trying to connect to a SPIRE socket that is not present.
=> fix spire UDS path typo

linkerd.io/content/2.15/common-errors/_index.md, linkerd.io/content/2.15/common-errors/failfast.md, linkerd.io/content/2.15/common-errors/http-502.md, linkerd.io/content/2.15/common-errors/http-503-504.md, linkerd.io/content/2.15/common-errors/protocol-detection.md, linkerd.io/layouts/partials/sidebar-2.html
This is obviously not a complete list -- it's meant to be a start that we add to.
=> Have a "common errors" page.

linkerd.io/content/2-edge/getting-started/_index.md, linkerd.io/content/2.15/getting-started/_index.md
As of Kubernetes 1.27, the `--short` arg to kubectl version is deprecated and prints a warning. As of Kubernetes 1.28, using it results in an error.
=> remove deprecated --short arg to kubectl version

.devcontainer/on-create.sh, linkerd.io/content/_index.md, linkerd.io/hugo.toml, linkerd.io/layouts/2.15/section.json, linkerd.io/layouts/_default/baseof.html, linkerd.io/layouts/index.searchindex.json, linkerd.io/layouts/partials/css.html, linkerd.io/static/robots.txt, linkerd.io/themes/buoyant/layouts/_default/baseof.html, linkerd.io/themes/buoyant/layouts/partials/head.html, linkerd.io/themes/buoyant/layouts/robots.txt, netlify.toml
Add search index for 2.15 docs
=> Add search index

linkerd.io/content/releases/_index.md
Add a versions section at the bottom of Releases and Versions. @kflynn at the risk of conflicting again with your PR, what do you think about something like this to capture the mapping between versions and release artifacts?
=> add Versions section

linkerd.io/content/blog/2024/0606-edge-release-roundup.md
Edge roundup for May 2024. I know it's June, but we're covering the May releases (it's likely that this one-month-in-arrears trend will continue).
=> Edge Roundup 2024-06

linkerd.io/content/2.15/tasks/install-helm.md
Closes linkerd/linkerd2#12753
When the helm repo is added we give it the name "linkerd-edge", so we should keep on using that name for the rest of the instructions.
=> Fix helm install instructions

linkerd.io/content/2.15/features/ha.md, linkerd.io/content/2.15/features/proxy-injection.md, linkerd.io/content/2.15/tasks/troubleshooting.md
This is now done by default and the check has been removed (see
https://github.com/linkerd/linkerd2/issues/12233). Update the docs accordingly.
=> document namespaces excluded from injection 

linkerd.io/layouts/partials/docs.html
This PR fixes the link in the old-version banner so it links to the corresponding latest page.
**Testing:**
Section page → https://deploy-preview-1809--linkerdio.netlify.app/2.14/features/
Regular page → https://deploy-preview-1809--linkerdio.netlify.app/2.14/features/ingress/
Fixes #1802
=> Old-version banner not linking to latest page

linkerd.io/hugo.toml, linkerd.io/themes/buoyant/layouts/partials/twitter-cards.html
In the latest release of Hugo, there's a couple warnings about deprecated collections that are being referenced:
```
WARN  deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in a future release. Use .Site.Params instead.
WARN  deprecated: .Site.Authors was deprecated in Hugo v0.124.0 and will be removed in a future release. Use taxonomies instead.
```
Currently, neither one of these collections are configured in `hugo.toml`, so the meta tag for `twitter:site` and `twitter:creator` are not being rendered.
This PR addresses these warnings, with the following changes: 
`.Site.Social.twitter` has been updated to use `site.Params.social.twitter`, and this property has been set in `hugo.toml`, so `twitter:site` will now be rendered.
Support for `twitter:creator` has …
=> Fix deprecated warnings for .Site.Social and .Site.Authors

linkerd.io/content/2.15/reference/k8s-versions.md
=> Update supported Kubernetes versions

linkerd.io/content/2.16/features/ipv6.md, linkerd.io/hugo.toml
~This also enables emojis for the entire site.~
Short and sweet.
=> Feature article for IPv6

linkerd.io/content/2.15/features/server-policy.md, linkerd.io/content/2.16/features/server-policy.md, linkerd.io/content/2.16/reference/authorization-policy.md, linkerd.io/content/2.16/tasks/restricting-access.md
- Added Audit Mode section to the Authorization Policy feature article.
- Expanded the reference doc for `Servers` to include the new `accessPolicy` field.
- Updated the "Further Considerations" section in the Restricting Access To Services article to account for audit mode.
=> Audit mode

bin/export-channel-versions
To grab the latest public stable, we need to go back quite a bit in time. The default pagination of 30 was not enough to include the latest stable. Eventually, this will cause trouble again so we need to figure out what to do with this logic. For now, this should unblock the edge release that was failing: https://github.com/linkerd/linkerd2/actions/runs/10826210923/job/30038512028
=> gh-api: list more releaeses per page

linkerd.io/content/2.16/features/protocol-detection.md
- Clean up and clarify various bits of language
- Add NATS to the list of protocols that need opaque ports
- Instruct that the resource should always be set on the Service resource
In the interests of simplicity, I kept the guidance around setting the annotation at the Service resource relatively simple.
This content probably needs to be moved into a separate Reference doc. I did not do that in this doc.
=> update protocol detection doc

linkerd.io/content/2-edge/reference/httproute.md, linkerd.io/content/2.13/reference/httproute.md, linkerd.io/content/2.14/reference/httproute.md, linkerd.io/content/2.15/reference/httproute.md, linkerd.io/content/2.16/reference/httproute.md
while reviewing the documentation for `HTTPRoute` i found a number of broken links, a few of which were visibly misrendering on the website. this addresses most of these warnings (_i refrained from addressing `line-length` warnings_) and fixes the broken links. these fixes are applied to `2-edge` and backported to `2.13`, `2.14`, `2.15`, and `2.16` releases.
- fix broken `GEP-1426` links
- fix links to `#parentreference` anchor
- fix links to `Server` authorization policy
=> docs(reference): fix broken lints and address `markdownlint` warnings

linkerd.io/content/2-edge/tasks/automatically-rotating-webhook-tls-credentials.md
```
linkerd jaeger install
--set webhook.externalSecret=true \
--set-file webhook.caBundle=ca.crt \
| kubectl apply -f -
```
this command is missing a `\` at the end of the first line.
=> Add missing \

linkerd.io/assets/scss/app/_adopters.scss, linkerd.io/assets/scss/app/_ambassadors.scss, linkerd.io/assets/scss/app/_enterprise.scss, linkerd.io/assets/scss/app/_get-involved.scss, linkerd.io/assets/scss/app/_heroes.scss, linkerd.io/assets/scss/app/_tests.scss, linkerd.io/assets/scss/components/_card.scss, linkerd.io/assets/scss/main.scss, linkerd.io/assets/scss/mixins/_card.scss, linkerd.io/content/tests/components.html, linkerd.io/layouts/enterprise/list.html
The card component has been refactored so that it no longer has breakpoint classes to be more consistent with other components, and to provide more flexibility. With this PR, if you want to change the options of the card at a breakpoint, apply a card mixin. For example:
Current:
```html
<div class="card card-md-reverse">...
```
With this PR:
```scss
@media (min-width: breakpoint-min-width("md")) {
.card {
@include make-card--reverse;
}
}
```
```html
<div class="card">...
```
Reviewers: You can verify the new card behavior on the Enterprise page:
https://deploy-preview-1872--linkerdio.netlify.app/enterprise/
=> Refactor card

linkerd.io/layouts/docs/_docs-nav.html, linkerd.io/layouts/shortcodes/docs/section-toc.html
Currently, if a section in the Docs sidenav only contains child sections and not any regular pages, the submenu will not be displayed for that section. The submenu should still be displayed in this case.
With this PR, the sidenav has been fixed to show a submenu of a section, if it only contains child sections. 
There are currently not any sections in the Docs sidenav that only contain other sections, but I'm fixing this bug just in case we do in the future.
Currently, the `section-toc` shortcode is incorrectly listing pages that have the `unlisted` param set.
With this PR, unlisted pages will not be shown when using the `section-toc` shortcode. 
There are currently not any index pages that use the `section-toc` shortcode and also have unlisted pages.
=> Fix 2 potencial bugs in docs

linkerd.io/content/2-edge/tasks/distributed-tracing.md
The docs are somewhat outdated here, as they blanket recommend OpenCensus over OpenTelemetry.
Now that OpenCensus is sunset and the proxy supports OpenTelemety, the docs have been updated to reflect that.
=> Update distributed tracing docs to include otel

linkerd.io/content/2-edge/features/protocol-detection.md, linkerd.io/content/2.16/features/protocol-detection.md
=> Minor protocol-detection doc tweak

linkerd.io/content/faq/_index.md
- Fixed broken security audit link
- Fixed broken link to roadmap file which no longer exists
- Fixed grammar where we should be using 'as' instead of 'is'
- Removed some whitespace
=> Updating FAQ

linkerd.io/content/2-edge/tasks/configuring-proxy-concurrency.md, linkerd.io/content/2.10/tasks/configuring-proxy-concurrency.md, linkerd.io/content/2.11/tasks/configuring-proxy-concurrency.md, linkerd.io/content/2.12/tasks/configuring-proxy-concurrency.md, linkerd.io/content/2.13/tasks/configuring-proxy-concurrency.md, linkerd.io/content/2.14/tasks/configuring-proxy-concurrency.md, linkerd.io/content/2.15/tasks/configuring-proxy-concurrency.md, linkerd.io/content/2.16/tasks/configuring-proxy-concurrency.md, linkerd.io/content/2.17/tasks/configuring-proxy-concurrency.md
Fixed incorrect value in the deployment manifest example on the Configuring Proxy Concurrency task page.
Fixes [#1808](https://github.com/linkerd/website/issues/1808)
=> Fix incorrect value in Configuring Proxy Concurrency task page

linkerd.io/content/2-edge/reference/k8s-versions.md
=> Update 2-edge K8s versions

linkerd.io/content/2-edge/tasks/external-prometheus.md, linkerd.io/content/2.13/tasks/external-prometheus.md, linkerd.io/content/2.14/tasks/external-prometheus.md, linkerd.io/content/2.15/tasks/external-prometheus.md, linkerd.io/content/2.16/tasks/external-prometheus.md, linkerd.io/content/2.17/tasks/external-prometheus.md
Originally by @JadKHaddad in #1659, thanks!
- **Subject: Communication Issue Between Viz and External Prometheus**
- **Example without basic auth added. Same changes in 2.14 done**
- **Update for 2.14+, and talk about basic-auth Secrets for 2.17 & 2-edge.**
=> Prometheus basic-auth fixes

linkerd.io/content/2-edge/reference/authorization-policy.md, linkerd.io/content/2.12/reference/authorization-policy.md, linkerd.io/content/2.13/reference/authorization-policy.md, linkerd.io/content/2.14/reference/authorization-policy.md, linkerd.io/content/2.15/reference/authorization-policy.md, linkerd.io/content/2.16/reference/authorization-policy.md, linkerd.io/content/2.17/reference/authorization-policy.md
An AuthorizationPolicy cannot target a resource in another namespace, as this would allow one namespace to grant access to another's resources.  This is codified in the CRD as the `targetRef` does not have a `namespace` field.  However, our docs incorrect claim that it does have a `namespace` field.
We correct this error by removing references to the non-existent field and clarifying that only the namespace which can be targeted is the local one.
=> Fix AuthorizationPolicy docs to indicate that targetRef cannot include a namespace

linkerd.io/content/2-edge/tasks/adding-non-kubernetes-workloads.md, linkerd.io/content/2.15/tasks/adding-non-kubernetes-workloads.md, linkerd.io/content/2.16/tasks/adding-non-kubernetes-workloads.md, linkerd.io/content/2.17/tasks/adding-non-kubernetes-workloads.md
SPIFFE link in docs points to `spiffee.io` which is a non-existent domain and is likely a typo.  corrected the url to point to `spiffe.io`.
=> fix spiffe link url typo

linkerd.io/content/2.17/tasks/configuring-dynamic-request-routing.md
Two links that go to HTTPRoute
=> Fix misdirected link to GRPCRoute

linkerd.io/content/2-edge/tasks/configuring-proxy-concurrency.md
The proxy's configuration has been updated to support "rational" CPU limits. This change reorganizes the Proxy configuration guide to describe the new configuration.
=> chore(tasks): update configuring-proxy-concurrency

linkerd.io/content/2-edge/reference/multicluster.md
This accounts for the work from linkerd/linkerd2#13783 and linkerd/linkerd2#13802 where we defined the criteria for copying metadata (labels, annotations and ports) from mirrored services into federated services.
=> Add "Metadata Coyping" section to the multicluster ref doc

linkerd.io/content/2-edge/features/protocol-detection.md
this commit makes a small patch to the documentation of the `linkerd.io/tcp` directive, fixing a typo in the note's text.
=> nit(features): address typo in `linkerd.io/tcp` note

linkerd.io/content/2-edge/tasks/managing-egress-traffic.md
* quote annotation value so that it isn't treated as a boolean
* use correct client pod name
* use v1 HTTPRoute resource version
=> fix minor issues in egress docs

linkerd.io/layouts/docs/_docs-deprecated-alert.html
At some point the deprecated alert in the older docs stopped working. This PR fixes the logic so an old doc will once again link to the latest version of the doc.
To test, verify that the link in the deprecated alert...
https://deploy-preview-1970--linkerdio.netlify.app/2.15/tasks/automatic-failover/
goes to this page...
https://deploy-preview-1970--linkerdio.netlify.app/2.18/tasks/automatic-failover/
=> Fix deprecated alert

linkerd.io/content/2.16/reference/grpcroute.md, linkerd.io/content/2.16/reference/httproute.md, linkerd.io/content/2.17/reference/grpcroute.md, linkerd.io/content/2.17/reference/httproute.md, linkerd.io/content/2.18/reference/grpcroute.md, linkerd.io/content/2.18/reference/httproute.md
It appears that a few link references got orphaned when the Gateway API docs were [reworked](https://github.com/linkerd/website/pull/1909). 
@wmorgan Specifically in the GRPCRoute reference doc, is the timeout link going to the right place? I wasn't sure if it should go to the feature page or the reference page.
https://deploy-preview-1973--linkerdio.netlify.app/2.18/reference/httproute/
https://deploy-preview-1973--linkerdio.netlify.app/2.18/reference/grpcroute/
https://deploy-preview-1973--linkerdio.netlify.app/2.17/reference/httproute/
https://deploy-preview-1973--linkerdio.netlify.app/2.17/reference/grpcroute/
https://deploy-preview-1973--linkerdio.netlify.app/2.16/reference/httproute/
https://deploy-preview-1973--linkerdio.netlify.app/2.16/reference/grpcroute/
=> Fix broken links in httproute and grpcroute docs

linkerd.io/layouts/partials/page-description.html
Currently, when the `.Summary` is use for the meta description because the `.Description` value is empty, the summary content is not truncated. Because of this, the length of the summary can be longer than the recommended length of a page description.
With this PR, when the summary is used as the page description, it is truncated to 160 characters.
=> Truncate summary when used as page description

bin/export-channel-versions
Previously, the scripts would try to infer the bin directory from the script arguments, which isn't consistent. This updates it to simply reference the bin directory directly.
=> fix(ci): Fix bindir in validate scripts

.github/workflows/install.yml, .github/workflows/validate.yml, bin/export-channel-versions, bin/scurl
Some shells can unescape newlines (\n) in script variables, this prevents that by dumping the json to a file and having jq read from that directly.
=> fix(ci): Read releases json from file

linkerd.io/README.md, linkerd.io/assets/scss/components/_img-ratio.scss, linkerd.io/assets/scss/main.scss, linkerd.io/content/tests/components.html, linkerd.io/layouts/blog/_feature.html
With this PR, the featured images on the blog post listing page maintain a 4x1 aspect ratio on all screen sizes.
**Preview**
https://deploy-preview-2008--linkerdio.netlify.app/blog/
To test this change locally, you can feature a blog post with a cover image that is not in 4x1 ratio, such as `/blog/2024/1205-announcing-linkerd-2.17`.
=> Maintain consistent image ratio on blog post feature images

linkerd.io/content/enterprise/_index.md
Subject
Fix enterprise training link/redirect
Problem
Users navigating from /enterprise end up at an archived/outdated LF course page, causing confusion.
Solution
- Remove stale Netlify redirect for /enterprise (if present) and point to the actual Enterprise page.
- Update the training link on the Enterprise page to a currently maintained edX listing.
Fixes #2025
=> Fix enterprise training link/redirect

linkerd.io/content/2.11/tasks/multicluster-using-statefulsets.md, linkerd.io/content/2.12/tasks/multicluster-using-statefulsets.md, linkerd.io/content/2.13/tasks/multicluster-using-statefulsets.md, linkerd.io/content/2.14/tasks/multicluster-using-statefulsets.md, linkerd.io/content/2.15/tasks/multicluster-using-statefulsets.md, linkerd.io/content/2.17/tasks/multicluster-using-statefulsets.md
Fixes a small typo in the multicluster statefulsets task where the `--set "enableHeadlessServices=true"` flag was missing the closing quote. The typo appears in versions **2.13**, **2.14**, **2.15**, and **2.17** of the page.
An unmatched quote can trip up copy/paste and confuse readers. This change restores the closing quote and keeps the flag syntactically correct.
Docs-only change; no behavior modification.
- `linkerd.io/content/2.13/tasks/multicluster-using-statefulsets.md`
- `linkerd.io/content/2.14/tasks/multicluster-using-statefulsets.md`
- `linkerd.io/content/2.15/tasks/multicluster-using-statefulsets.md`
- `linkerd.io/content/2.17/tasks/multicluster-using-statefulsets.md`
=> docs(multicluster): fix missing quote in headless services flag (2.13/2.14/2.15/2.17)
