- linkerd.io/content/2/inject-reference.mmark
Signed-off-by: Zach Arnold <me@zacharnold.org>
> Fix "Port" Spelling

- linkerd.io/content/1/features/transparent-proxying.md
> Fix spelling of Kubernetes

- linkerd.io/content/2/adding-your-service.md
- linkerd.io/content/2/architecture.md
- linkerd.io/content/2/automatic-tls.md
- linkerd.io/content/2/debugging-an-app.md
- linkerd.io/content/2/get-involved.md
- linkerd.io/content/2/getting-started.md
- linkerd.io/content/2/inject-reference.mmark
- linkerd.io/content/2/prometheus.md
- linkerd.io/content/2/proxy-metrics.md
- linkerd.io/content/2/upgrade.md
Note: this will need to be updated when more of the in flight things land in a release.
> Add upgrade and basic architecture doc

- linkerd.io/content/2/adding-your-service.md
- linkerd.io/content/2/automatic-tls.md
- linkerd.io/content/2/debugging-an-app.md
- linkerd.io/content/2/get-involved.md
- linkerd.io/content/2/inject-reference.mmark
- linkerd.io/content/2/next-steps.md
- linkerd.io/content/2/prometheus.md
- linkerd.io/content/2/proxy-metrics.md
- linkerd.io/content/2/upgrade.md
Next steps page feels sparse, but not sure what else to put there.  Suggestions welcome.
> Add next-steps and update email lists

- linkerd.io/config.toml
- linkerd.io/content/2/overview.md
- run.linkerd.io/public/install
- run.linkerd.io/public/install-edge
- versioncheck.linkerd.io/public/version.json
This is a follow-up to #19. Once we have a stable release, we'll prefer that for all of the web properties.
> Move site, install script and version check to stable

- README.md
- linkerd.io/config.toml
> Update Linkerd1 release doc, bump to 1.4.6

- Makefile
> Update linkerd edge release version to 18.9.3

- linkerd.io/config.toml
> Update Linkerd1 release doc, bump to 1.5.0

- Makefile
> Update to edge-18.10.2

- Makefile
> Update sites for edge-18.10.3 release

- linkerd.io/config.toml
> Update Linkerd site with 1.5.1 release

- linkerd.io/content/2/adding-your-service/_index.md
Fixes https://github.com/linkerd/linkerd2/issues/1845
> Add list of server speaks first protocols

- Makefile
> Bump linkerd2 version to edge-18.11.2

- Makefile
> Bump linkerd2 version to edge-18.11.3

- linkerd.io/layouts/partials/nav.html
> change Get Started nav button to point to cyp

- linkerd.io/content/2/upgrade/_index.md
Add instructions for upgrading Linkerd given the component renames that happened in linkerd/linkerd2#1920.
> Add upgrade notice for the 2.1 stable release

- Makefile
Update for the edge-18.12.2 / stable-2.1.0 releases.
> Update edge and stable versions

- linkerd.io/content/2/observability/proxy-metrics.md
> Update proxy metrics doc with routes metrics

- linkerd.io/config.toml
> 1.6.0 release docs

- Makefile
> Update for linkerd2 edge-19.1.2 release

- linkerd.io/content/2/faq/_index.md
> Add linkerd faq section for pre-k8s checks

- run.linkerd.io/public/emojivoto-daemonset.yml
- run.linkerd.io/public/emojivoto.yml
Based on BuoyantIO/emojivoto#59. Also bump both configs to v6
> Update emojivoto daemonset config

- linkerd.io/content/2/automatic-tls/_index.md
> Document TLS interaction with ELB

- linkerd.io/content/2/supported-protocols/_index.md
> add NATS and mongodb ports to server-speaks-first protocol list

- linkerd.io/content/2/cni/_index.md
Signed-off-by: Cody Vandermyn <cody.vandermyn@nordstrom.com>
Needs PR in linkerd2 #2181 to be merged for full relevance.
> Documentation for the CNI Plugin

- linkerd.io/content/2/cni/_index.md
This is a follow up to #114 (thanks @codeman9!). I mostly just reorganized to match the format of some of our other docs pages, and I removed some of the lower level details so as not to overwhelm new users. Eventually we'll want a more low-level description of how it all works, but I'm anticipating this page will mostly be used for getting started. I also wrapped all of the paragraphs at 80 characters, as I'm wont to do.
> Updates to linkerd-cni plugin documentation

- linkerd.io/config.toml
> 1.6.1 release

- Makefile
Fixes #119
Tested fine in both Linux and Mac.
> Fix build in Linux

- linkerd.io/content/1/advanced/routing.md
Just removed a couple of extra words.
Signed-off-by: Martin Mosegaard Amdisen <martinmosegaard@gmail.com>
> Update to advanced routing page

- linkerd.io/content/2/faq/_index.md
Relates to linkerd/linkerd2#2197
> Fix spelling on linkerd check link

- linkerd.io/content/gsoc.md
> Minor edits to the GSOC page

- linkerd.io/content/2/getting-started/_index.md
I went through this with a non-technical user and they stumbled
on one or two things, which I've tried to correct below.
> minor tweaks to the Getting Started guide

- linkerd.io/content/2/proxy-injection/_index.md
In #127 I updated the auto-inject page to describe the new setup that's shipping with the next edge release. Have clarified the wording on that page to hopefully make it clearer what has changed.
> Tweak note about auto-injection behavior change

- Makefile
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>
> Update version to edge-19.2.1

- run.linkerd.io/public/booksapp.yml
Follow up from BuoyantIO/booksapp#14
> Update booksapp to match repo version

- Makefile
> Update site for edge-19.2.2 release

- linkerd.io/content/2/features/http-grpc.md
- linkerd.io/content/2/features/protocol-detection.md
- linkerd.io/content/2/features/proxy-injection.md
> Fix broken links on some features pages

- linkerd.io/content/2/features/_index.md
- linkerd.io/content/2/features/telemetry.md
> Fix TOC on Features page, also telemetry links

- linkerd.io/content/2/cli/routes.md
Signed-off-by: Mohammad Banikazemi MBanikazemi@gmail.com
> fixes a broken link

- linkerd.io/content/2/upgrade/_index.md
- linkerd.io/data/cli.yaml
> Add upgrade guide for 2.1 -> 2.2

- Makefile
> Update site for edge-19.2.3 release

- linkerd.io/Makefile
- netlify.toml
> Add Netlify configuration for linkerd.io

- Makefile
> Update for the linkerd2 stable-2.2.1 release

- linkerd.io/content/1/getting-started/k8s.md
- linkerd.io/content/1/tutorials/part-eight.md
- linkerd.io/content/1/tutorials/part-five.md
- linkerd.io/content/1/tutorials/part-four.md
- linkerd.io/content/1/tutorials/part-nine.md
- linkerd.io/content/1/tutorials/part-one.md
- linkerd.io/content/1/tutorials/part-six.md
- linkerd.io/content/2/features/ingress.md
- linkerd.io/content/2/overview/_index.md
- linkerd.io/content/2/tasks/exporting-metrics.md
- linkerd.io/content/2/tasks/troubleshooting.md
- linkerd.io/layouts/partials/admonition.html
- linkerd.io/layouts/partials/footer.html
- linkerd.io/layouts/shortcodes/note.html
This is a purely aesthetic PR that adds a Note admonition block and provides scaffolding for other blocks (warning, danger, success, etc.) should we want to provide those in the future.
Here's an example:
> Add Note admonition block

- linkerd.io/layouts/partials/nav.html
> Add spacing in navbar

- linkerd.io/content/2/tasks/install.md
- linkerd.io/content/2/tasks/uninstall.md
> Add uninstall task

- linkerd.io/content/2/tasks/exporting-metrics.md
Signed-off-by: Jon Richards jon.richards@nordstrom.com
> Update Prometheus URL to use correct service name

- Makefile
> Bump edge version in Makefile

- linkerd.io/content/2/getting-started/_index.md
> Add note on automated proxy injection to Getting Started guide

- linkerd.io/content/2/tasks/exposing-dashboard.md
> Remove origin header so that it does not clash with the host header

- README.md
- linkerd.io/Makefile
This PR adds `lint` and `check` targets to the linkerd.io `Makefile` and updates the `README` instructions for building with Hugo.
> Modifying Makefile and updating README Hugo development instructions

- Makefile
> Update sites for edge-19.3.2 release

- run.linkerd.io/public/emojivoto-daemonset.yml
- run.linkerd.io/public/emojivoto.yml
Relates to buoyantio/emojivoto#65
> Bump emojivoto to v7

- Makefile
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>
> Bump version for edge-19.4.1

- README.md
> Update set up instructions for Linux users

- Makefile
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>
> Bump version for edge-19.4.2

- linkerd.io/content/2/design-principles/_index.md
> add basic design principles doc

- Makefile
Depends on linkerd/linkerd2#2670
> Update for edge-19.4.3

- run.linkerd.io/public/emojivoto-daemonset.yml
- run.linkerd.io/public/emojivoto.yml
> update emojivoto version in manifests

- Makefile
> Update site for edge-19.4.4

- Makefile
- linkerd.io/.htmltest.yml
- linkerd.io/content/2/features/automatic-tls.md
- linkerd.io/content/2/features/dashboard.md
- linkerd.io/content/2/features/ha.md
- linkerd.io/content/2/features/ingress.md
- linkerd.io/content/2/features/load-balancing.md
- linkerd.io/content/2/features/proxy-injection.md
- linkerd.io/content/2/features/service-profiles.md
- linkerd.io/content/2/features/telemetry.md
- linkerd.io/content/2/reference/architecture.md
- linkerd.io/content/2/tasks/upgrade.md
- linkerd.io/content/dashboard/20190416.md
- linkerd.io/data/cli.yaml
- update version in Makefile
- add `upgrade` instructions
- community update
- TLS update
- update CLI reference
Fixes #255, #259, #260
> Update website for stable-2.3.0 release

- linkerd.io/content/2/getting-started/_index.md
- linkerd.io/content/2/tasks/debugging-your-service.md
Signed-off-by: Diogenes Rettori <rettori@gmail.com>
> fixed name of the emoji

- linkerd.io/content/2/tasks/books.md
the whole example (but this part) is assuming that the sp would be on ns booksapp
Signed-off-by: Diogenes Rettori <rettori@gmail.com>
> books demo: fixed namespace-name on FQDN for authors sp

- linkerd.io/content/blog/announcing-linkerd-2-0.md
- linkerd.io/layouts/index.html
Signed-off-by: Alejandro Pedraza <alejandro.pedraza@gmail.com>
> Remove references to Hush

- Makefile
Signed-off-by: Alejandro Pedraza <alejandro@buoyant.io>
> Update site for edge-19.4.5

- linkerd.io/content/2/tasks/upgrade.md
> Add docs for upgrading via manifests

- Makefile
- linkerd.io/.htmltest.yml
> edge-19.5.1

- linkerd.io/content/dashboard/20190506.md
> add 20190506.md

- Makefile
> Update edge version to 19.5.2

- linkerd.io/config.toml
> update docs to linkerd 1.6.3

- .circleci/config.yml
- linkerd.io/content/2/tasks/using-ingress.md
- linkerd.io/content/blog/icymi-may-2019-san-francisco-linkerd-meetup.md
> fix up some lint errors

- linkerd.io/config.toml
> update the site-wide description

- linkerd.io/content/2/tasks/books.md
@andreasottosson pointed out in #265 that the timeouts example in the books app demo task didn't make a lot of sense. This PR restructures that section to fix it, and addresses a few other typos.
> Fix service profile timeout example in books demo task

- linkerd.io/content/blog/linkerd-benchmarks.md
> update benchmark blost with kinvolks's update

- Makefile
> update website with stable-2.3.1 version

- Makefile
Update the Makefile to `edge-19.5.4`
> Updating edge release number to 19.5.4

- Makefile
> Update website for stable-2.3.2

- Makefile
> update edge to 19.6.1

- linkerd.io/content/dashboard/20190606.md
> Add stable-2.3.2 to dashboard announcements

- Makefile
> Update edge version to edge-19.6.2

- linkerd.io/layouts/partials/community/jobs.html
- linkerd.io/layouts/partials/enterprise/support.html
- fix jobs banner text color
- fix enterprise page button size
> Design fixes

- linkerd.io/content/_index.md
- linkerd.io/content/community.md
> update form links, and minor wordsmithing

- linkerd.io/content/_index.md
> Update download banner

- linkerd.io/content/dashboard/20190619.md
> Add community update for linkerd community meeting

- linkerd.io/assets/scss/styles.scss
Closes https://github.com/linkerd/website/issues/355
> Fix homepage twitter card size for no js

- linkerd.io/content/community.md
- linkerd.io/layouts/partials/community/jobs.html
- linkerd.io/layouts/partials/community/top-hero.html
- linkerd.io/layouts/partials/hero.html
- Added target="blank" to templates
- Updated "Create Pull Request" jobs link to open GitHub editor for community.md
> Open community links in a new tab

- Makefile
> Bump edge version to edge-19.6.3

- linkerd.io/content/2/getting-started/_index.md
This PR is related to solve this issue https://github.com/linkerd/linkerd2/issues/2940 🎉
> Add additional GKE steps in getting started guide

- linkerd.io/content/2/getting-started/_index.md
- linkerd.io/content/2/tasks/install.md
> Move GKE private cluster configuration instructions to installation section

- linkerd.io/assets/scss/styles.scss
- linkerd.io/layouts/1/getting-started.html
- linkerd.io/layouts/_default/baseof.html
- linkerd.io/layouts/partials/choose-your-platform/platform.html
- linkerd.io/layouts/partials/get-started.html
> fix: fix getting started page

- linkerd.io/config.toml
- linkerd.io/content/1/administration/_index.md
- linkerd.io/content/1/advanced/_index.md
- linkerd.io/content/1/configuration/_index.md
- linkerd.io/content/1/examples/_index.md
- linkerd.io/content/1/features/_index.md
- linkerd.io/content/1/getting-started/_index.md
- linkerd.io/content/1/overview/_index.md
- linkerd.io/content/1/support/_index.md
- linkerd.io/content/1/tutorials/_index.md
> Update the sidebar menu order for linkerd 1

- linkerd.io/content/2/getting-started/_index.md
- linkerd.io/content/2/reference/cluster-configuration.md
- linkerd.io/content/2/tasks/install.md
- linkerd.io/content/2/tasks/troubleshooting.md
> Add cluster specific configuration section

- Makefile
> edge-19.6.4

- linkerd.io/content/2/tasks/troubleshooting.md
Linkerd 2.4 introduces several new checks, as part of the
`linkerd check` command:
- `pre-l5d-existence`
- `l5d-existence-mwc`
- `l5d-existence-vwc`
- `l5d-existence-psp`
- `l5d-existence-linkerd-config`
- `l5d-existence-replicasets`
- `l5d-existence-unschedulable-pods`
Depends on https://github.com/linkerd/linkerd2/pull/3017
Fixes #372
> Update Troubleshooting page with new 2.4 checks

- Makefile
> update edge to 19.7.1

- linkerd.io/content/2/tasks/using-psp.md
> Add PSP doc

- linkerd.io/content/2/tasks/using-debug-endpoints.md
> Add task 'Using Debugging Endpoints'

- Makefile
> edge-19.7.2

- linkerd.io/content/2/features/ha.md
- linkerd.io/data/cli.yaml
Relates to https://github.com/linkerd/linkerd2/issues/2419
Depends on https://github.com/linkerd/linkerd2/pull/3049
> Mark High Availability as non-experimental

- linkerd.io/content/2/tasks/using-the-debug-container.md
Fixes https://github.com/linkerd/website/issues/279
> 2.4 - Add documentation on using the debug container

- Makefile
> Bump stable version to stable-2.4.0

- linkerd.io/content/2/tasks/troubleshooting.md
Relates to https://github.com/linkerd/linkerd2/issues/3054
Depends on https://github.com/linkerd/linkerd2/pull/3055
> Add troubleshooting section for NET_RAW check

- linkerd.io/layouts/partials/meta.html
> use thumbnail images for twitter card images

- linkerd.io/content/2/features/telemetry.md
> Add golden metrics description

- linkerd.io/content/2/tasks/using-the-debug-container.md
> add a bit more to debug container task

- Makefile
Signed-off-by: Alejandro Pedraza Borrero <alejandro@buoyant.io>
> edge-19.7.4 release

- linkerd.io/content/2/features/ha.md
> update HA docs

- linkerd.io/content/blog/failure-injection-using-the-service-mesh-interface-and-linkerd.md
> Add thumbnail

- linkerd.io/content/2/tasks/books.md
Signed-off-by: mickey.boxell <mickey.boxell@oracle.com>
> Adding clean up section

- linkerd.io/content/2/tasks/using-psp.md
> Fix YAML in using PSP

- linkerd.io/content/2/tasks/using-psp.md
> Update PodSecurityPolicy Name

- linkerd.io/layouts/blog/single.html
Let's see if this helps, otherwise we'll put it in the footer.
> fix(performance): load addthis script asynchronously

- linkerd.io/content/2/tasks/troubleshooting.md
> Add troubleshooting note about service profile versions

- linkerd.io/assets/js/search.js
- linkerd.io/layouts/partials/community/jobs.html
- linkerd.io/layouts/partials/enterprise/support.html
- linkerd.io/layouts/partials/featured-card.html
- linkerd.io/static/images/linkerd_mark_grid_large.svg
- linkerd.io/themes/buoyant/layouts/partials/featured-card.html
- linkerd.io/themes/buoyant/layouts/partials/related-card.html
> fix: use linkerd logo as default thumbnail

- Makefile
> Bump edge version to edge-19.7.5

- linkerd.io/content/2/features/distributed-tracing.md
> initial distributed tracing doc

- linkerd.io/content/blog/icymi-july-linkerd-community-meetup.md
> fix up blog post in various ways

- Makefile
> Update edge version for edge-19.8.1

- linkerd.io/content/2/tasks/canary-release.md
Clarify the background and motivation of why we're doing this.
> clarify and motivate flagger canary task

- linkerd.io/content/2/tasks/using-ingress.md
Signed-off-by: Robert Sayre <sayrer@gmail.com>
> Add GCE ingress instructions.

- Makefile
Depends on https://github.com/linkerd/linkerd2/pull/3265
> Bumping edge version to 19.8.3

- linkerd.io/content/2/tasks/securing-your-cluster.md
> Update Tap RBAC page for 2.5.0, dashboard support

- linkerd.io/content/2/tasks/install-helm.md
User-facing Helm instructions.
> Add Helm install instructions

- Makefile
Depends on https://github.com/linkerd/linkerd2/pull/3272
> Bumping edge version to 19.8.4

- Makefile
Depends on https://github.com/linkerd/linkerd2/pull/3285
> Bumping edge version to 19.8.5

- Makefile
> Update edge version to 19.8.6

- linkerd.io/config.toml
> update linkerd 1.x version to 1.7.0

- Makefile
> update makefile to 19.8.7

- Makefile
> edge-19.9.1

- linkerd.io/content/_index.md
- linkerd.io/content/blog/happy-birthday-linkerd.md
> add happy birthday blog post

- Makefile
- linkerd.io/content/blog/happy-birthday-linkerd.md
Signed-off-by: Alejandro Pedraza Borrero <alejandro@buoyant.io>
> edge-19.9.3

- linkerd.io/content/2/tasks/troubleshooting.md
Depends on https://github.com/linkerd/linkerd2/pull/3524
> Add new troubleshooting section about data plane proxy CA check

- Makefile
> Update edge version to edge-19.10.3 for website

- Makefile
Signed-off-by: zaharidichev <zaharidichev@gmail.com>
> Update edge version to edge-19.10.4 for website

- Makefile
> update edge version to 19.10.5

- linkerd.io/content/2/features/distributed-tracing.md
- linkerd.io/content/2/tasks/distributed-tracing.md
> add distributed tracing guide, cribbed from Alex's post

- linkerd.io/content/dashboard/20191104.md
Will you be joining us later this month at Kubecon NA in San Diego? The Linkerd maintainers will be running a [Linkerd in Production workshop](https://kccncna19.sched.com/event/SbVx/a-linkerd-in-production-workshop-hosted-by-buoyant-additional-registration-fee-required). Join us! (Scholarships are available for contributors, individuals, and those in need. Email events@buoyant.io for details.)
For the complete list of the many Linkerd events at this year's Kubecon NA, be sure to check out the [Linkerd Community Guide to KubeCon NA 2019](https://buoyant.io/2019/10/10/linkerd-community-guide-to-kubecon-na-2019/).
> announce workshop in dashboard

- Makefile
> Update Makefile edge version to edge-19.11.1

- linkerd.io/data/cli.yaml
- linkerd.io/layouts/partials/cli/annotations.html
- linkerd.io/layouts/shortcodes/cli.html
- linkerd.io/layouts/shortcodes/cli/annotations.html
- linkerd.io/layouts/shortcodes/cli/description.html
- linkerd.io/layouts/shortcodes/cli/examples.html
- linkerd.io/layouts/shortcodes/cli/flags.html
Fixes https://github.com/linkerd/linkerd2/issues/3501
PR for `linkerd doc` command - https://github.com/linkerd/linkerd2/pull/3564
I believe that this one should be merged after it.
> rework for annotations from yaml

- linkerd.io/content/1/examples/external-resources.md
- linkerd.io/content/2/tasks/modifying-proxy-log-level.md
> Update proxy log doc to show usage of the new 'log level' endpoint

- linkerd.io/content/2/tasks/use_external_certs.md
- linkerd.io/data/cli.yaml
Fixes https://github.com/linkerd/linkerd2/issues/3662
Signed-off-by: zaharidichev <zaharidichev@gmail.com>
> Docs for cert-manager integration

- Makefile
> Update Makefile to point to edge-19.11.2

- linkerd.io/content/2/tasks/distributed-tracing.md
https://run.likerd.io/ -> https://run.linkerd.io/
> Fix typo in url

- linkerd.io/content/2/tasks/customize-install.md
Problem:
One cannot use `system-cluster-critical` or `system-node-critical` in any namespace other than `kube-system`
Solution:
Correct the example with a user-defined `PriorityClass`
Signed-off-by: Brian Warsing <dayglojesus@gmail.com>
> Correct PodPriority kustomization example (#596)

- Makefile
> Bump edge version to 19.12.1

- Makefile
> stable-2.6.1

- linkerd.io/content/2/getting-started/_index.md
- linkerd.io/content/2/tasks/troubleshooting.md
> Increase minimum k8s version to 1.13

- Makefile
> Update to edge-19.12.3

- linkerd.io/content/2/tasks/setting-up-service-profiles.md
Signed-off-by: Derrick Burns <derrick@tidepool.org>
> Updated service profile description

- linkerd.io/content/2/tasks/upgrade.md
- linkerd.io/content/2/tasks/using-the-debug-container.md
- linkerd.io/content/blog/slow-cooker-load-testing-for-tough-software.md
This was transferred from https://github.com/linkerd/linkerd2/issues/3448, hence the branch name.
> Add docs for 617 and fix some lint/check issues

- linkerd.io/config.toml
> Update Linkerd 1 version to 1.7.1

- linkerd.io/content/2/tasks/generate-certificates.md
- linkerd.io/content/2/tasks/install-helm.md
- linkerd.io/content/2/tasks/use_external_certs.md
> Document that ECDSA P-256 is required

- Makefile
> update Makefile to edge-20.1.1

- linkerd.io/content/2/tasks/troubleshooting.md
Adds documentation that explains complements the work done in https://github.com/linkerd/linkerd2/pull/3813
> Add hint anchors for tls checks

- linkerd.io/content/2/tasks/troubleshooting.md
This add more details around the failures that might occur when the HA checks are ran.
> Add ha checks to troubleshooting.md

- Makefile
> edge-20.1.2

- linkerd.io/data/cli.yaml
Add new override annotations to API documentation.  These additional settings were added with linkerd/linkerd2#3873.
Signed-off-by: Paul Balogh <javaducky@gmail.com>
> Update annotation documentation given changes from #3873

- linkerd.io/content/2/tasks/graceful-shutdown.md
Fixes https://github.com/linkerd/website/issues/623
> Add graceful shutdown doc

- linkerd.io/content/2/features/cni.md
- linkerd.io/content/2/tasks/install-helm.md
Modifies docs to include instructions of how to install CNI with Helm.
Fixes #602
> Add docs, detailing how to install CNI with Helm

- Makefile
> Bump edge version to edge-20.1.3

- Makefile
> Update Makefile to use edge-20.1.4

- run.linkerd.io/public/emojivoto-daemonset.yml
- run.linkerd.io/public/emojivoto-statefulset.yml
Also introduce `emojivoto-statefulset.yml`.
Relates to buoyantio/emojivoto#85
> Update emojivoto example workload manifests

- Makefile
> edge-20.2.1

- Makefile
- linkerd.io/data/cli.yaml
> stable-2.7.0

- linkerd.io/content/2/tasks/troubleshooting.md
Add troubleshooting docs for the CNI checks.
Fixes #628
> Add troubleshooting section for CNI checks

- linkerd.io/content/gsoc.md
Some updates for the GSoC 2020. I included a few items which I think are the FAQs, including:
* Where to find "good first issues"
* Read the DCO
* Where to find the BUILD instructions
* Submitting RFCs to the RFC repo
* The weekly email template used last year
* etc.
> Updates for GSoC 2020

- linkerd.io/content/gsoc.md
> Update GSoC page to reference the gsoc repo

- run.linkerd.io/public/booksapp.yml
Relates to BuoyantIO/booksapp#19
> Set k8s part-of labels on booksapp

- linkerd.io/content/2/features/cni.md
Some info on how to upgrade the CNI plugin. 
> Cni upgrade instructions

- linkerd.io/content/2/tasks/upgrade.md
Adds a note, calling out the changes to the Helm chart
> Helm upgrade note

- linkerd.io/content/2/tasks/using-ingress.md
Fixes https://github.com/linkerd/linkerd2/issues/3619
> Document nginx-ingress auth-url snippet

- .github/workflows/publish.yml
Explanation in linkerd/linkerd2#4100
> Add trigger for linkerd/linkerd2 release events

- linkerd.io/content/2/tasks/using-ingress.md
Refs #671
Documentation for https://github.com/linkerd/linkerd2/pull/4092
> Add contour ingress documentation

- linkerd.io/content/blog/serverless-service-mesh-with-knative.md
> add link to ambassador

- linkerd.io/content/2/tasks/using-a-private-docker-repository.md
Signed-off-by: Michael Randers-Pehrson <michael.rp@gmail.com>
> Add closing angled bracket

- linkerd.io/content/2/overview/_index.md
- linkerd.io/content/_index.md
- linkerd.io/layouts/partials/homepage/stats-list.html
> improve overview

- linkerd.io/content/2/tasks/troubleshooting.md
> Add tap api-service troubleshooting doc

- run.linkerd.io/public/booksapp.yml
- run.linkerd.io/public/emojivoto-daemonset.yml
- run.linkerd.io/public/emojivoto-statefulset.yml
- run.linkerd.io/public/emojivoto.yml
> Avoid LoadBalancer services in demo applications

- linkerd.io/content/2/faq/_index.md
- linkerd.io/content/blog/linkerd-and-open-governance.md
> clarify message

- linkerd.io/config.toml
> Update docs for linkerd 1.7.3

- run.linkerd.io/public/booksapp.yml
[Updated activeresource in booksapp](https://github.com/BuoyantIO/booksapp/pull/22) and this commit updates the version of the yaml file to use the version with the update.
> Update booksapp to v0.0.5

- linkerd.io/content/blog/announcing-linkerd-2-8.md
> update ambassador blog post link

- linkerd.io/content/2/tasks/using-ingress.md
> Add Traefik CRD definitions

- api.linkerd.io/build
- linkerd.io/config.toml
> Update docs for Linkerd 1.7.4

- linkerd.io/content/blog/announcing-linkerd-2-8.md
> remove duplicate title

- linkerd.io/content/1/tutorials/part-one.md
- linkerd.io/content/2/tasks/upgrade.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-i-top-line-service-metrics.md
- linkerd.io/data/cli.yaml
Explanation in linkerd/linkerd2#4613
> Fix upgrade docs

- linkerd.io/content/2/tasks/using-ingress.md
As verified in https://github.com/linkerd/linkerd2/issues/4636
> Update nginx ingress docs regarding default backends

- linkerd.io/config.toml
- linkerd.io/layouts/blog/rss.xml
- linkerd.io/layouts/partials/head.html
- linkerd.io/layouts/partials/rss.html
Added rss link in header html tag
Signed-off-by: Dimitri Pommier shokohsc@gmail.com
> #674 Blog RSS feed

- linkerd.io/content/blog/announcing-linkerd-2-8.md
> fix Naseem's name

- linkerd.io/content/2/tasks/uninstall.md
> Update control plane uninstallation doc

- linkerd.io/content/2/faq/_index.md
- linkerd.io/content/2/overview/_index.md
- linkerd.io/content/2/tasks/multicluster.md
- linkerd.io/content/blog/announcing-linkerd-2-4.md
- linkerd.io/content/blog/browser-testing-from-scratch-building-quick-and-easy-integration-tests-with-webdriverio-and-saucelabs.md
- linkerd.io/content/blog/happy-birthday-linkerd.md
- linkerd.io/content/gsoc.md
> update references from master -> main

- linkerd.io/content/2/tasks/using-ingress.md
Relates to linkerd/linkerd2#4211
> Add note about numeric service ports for Ingress

- linkerd.io/content/2/features/cni.md
- linkerd.io/content/2/tasks/automatically-rotating-control-plane-tls-credentials.md
- linkerd.io/content/2/tasks/generate-certificates.md
- linkerd.io/content/2/tasks/install-helm.md
https://www.dailywritingtips.com/depreciate-vs-deprecate/
> spelling: deprecated

- run.linkerd.io/public/install
- run.linkerd.io/public/install-edge
- Add checking the machine arch for an arm machine and download the correct binary file.
Merge before https://github.com/linkerd/linkerd2/pull/4841
> Support ARM CLI

- linkerd.io/content/blog/happy-birthday-linkerd.md
Fix `Lint html and check for dead links` as reported in https://github.com/linkerd/website/runs/955191928
> figo merged into finleap

- linkerd.io/content/blog/the-roadmap-for-linkerd-proxy.md
> fix date on oliver's blog post

- README.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-iv-continuous-deployment-via-traffic-shifting.md
- linkerd.io/content/blog/happy-birthday-linkerd.md
- linkerd.io/content/blog/the-roadmap-for-linkerd-proxy.md
> Fix broken link and CI errors

- README.md
> Update README to include Hugo version

- linkerd.io/content/2/tasks/using-ingress.md
Append ingress documentation for Kong
> Add Ingress documentation for Kong

- linkerd.io/content/2/features/multicluster.md
Some minor doc changes I stumbled upon while reading the docs.
Thank you for a great project 🙏
> Fix wording of multicluster introduction

- linkerd.io/content/2/tasks/using-psp.md
Signed-off-by: Pankaj Tolani <pankaj.tolani@digizoo.com.au>
> fix dated doco for psp needed to run emojivoto sample app

- linkerd.io/content/2/tasks/automatically-rotating-control-plane-tls-credentials.md
> Fix line of bash and add version compatibility note for cert-manager

- linkerd.io/content/_index.md
- linkerd.io/layouts/partials/homepage/stats-list.html
(And fix Twitter cards while we're at it)
> update title and messaging

- linkerd.io/content/2/tasks/exposing-dashboard.md
> Update oauth2 config link

- linkerd.io/content/2/tasks/upgrade.md
- linkerd.io/content/community/_index.md
Signed-off-by: javaducky <javaducky@gmail.com>
> Fixing minor typo in upgrade documentation.

- linkerd.io/content/2/tasks/manually-rotating-control-plane-tls-credentials.md
Linkerd 2.9 changed the config map format. This means the command mentioned to get the current trust anchors PEM does not work anymore.
This adds command to the documentation, which works with the new config format.
Fixes #855
I wasn't sure if I should leave the command for Linkerd < 2.9 in there or replace it. Also not sure if `yq` is the best thing to use here. Happy to change to whatever you prefer.
> update cmd to get trust anchors for linkerd 2.9

- linkerd.io/themes/buoyant/layouts/partials/schema.html
> fix: remove product schema

- linkerd.io/content/_index.md
> update homepage messaging

- linkerd.io/data/cli.yaml
> Clarify format of skip-(inbound|outboud)-ports

- linkerd.io/content/2/tasks/automatically-rotating-control-plane-tls-credentials.md
Signed-off-by: Gabrielle Madden <49839049+gabriellemadden@users.noreply.github.com>
> Correct cert-manager resource documentation

- linkerd.io/content/dashboard/january-linkerd-online-community-meeting.md
Cleaned up some forestry smart quotes
> Remove smart quotes and fix lint for dashboard community message

- linkerd.io/layouts/index.html
- linkerd.io/layouts/partials/homepage/adopter-banner.html
#894 was out of sync with the master branch and attempts by zentered didn't resolve the sync
I manually pulled the changes to this branch so that they could be merged from within the repository, rather than from the fork
> Homepage reordering see #894

- linkerd.io/content/blog/january-linkerd-community-meeting.md
Signed-off-by: Paul Armstrong <paularmstrong@work-computer.local>
> Added January community meeting blog post

- linkerd.io/content/blog/a-linkerd-2-0-deep-dive-unboxing-debugging-and-monitoring-kubernetes-services-on-azure.md
- linkerd.io/content/blog/a-service-mesh-for-ecs.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-i-top-line-service-metrics.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-ii-pods-are-great-until-theyre-not.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-iv-continuous-deployment-via-traffic-shifting.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-ix-grpc-for-fun-and-profit.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-v-dogfood-environments-ingress-and-edge-routing.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-vi-staging-microservices-without-the-tears.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-vii-distributed-tracing-made-easy.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-viii-linkerd-as-an-ingress-controller.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-x-the-service-mesh-api.md
- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-xi-egress.md
- linkerd.io/content/blog/linkerd-steering-committee.md
- linkerd.io/content/blog/why-linkerd-doesnt-use-envoy.md
- linkerd.io/layouts/partials/homepage/featured-blogs.html
• Update homepage featured blog
• Fixed broken links in old blog posts
> Update featured blog, Fix broken links

- linkerd.io/content/blog/february-2021-linkerd-hero-nomination.md
> february hero blog edit

- linkerd.io/content/2/features/telemetry.md
> Fix typo with `linkerd routes` flag

- linkerd.io/content/2/tasks/installing-multicluster.md
- linkerd.io/content/2/tasks/multicluster.md
- linkerd.io/content/2/tasks/upgrade-multicluster.md
> [2.10] Update multicluster docs

- linkerd.io/layouts/partials/adopters/top-hero.html
Signed-off-by: Christian Mejlak <chris@mejlak.com>
> Update: adopters should wrap if more than four

- linkerd.io/layouts/shortcodes/sectiontoc.html
Signed-off-by: Christian Mejlak <chris@mejlak.com>
> Fix section toc to use relative permalinks

- linkerd.io/content/2/tasks/install.md
> [2.10] Update Install tasks in the light of Viz

- linkerd.io/content/2/features/protocol-detection.md
> Update protocol detection docs with opaque ports

- linkerd.io/content/2.10/tasks/manually-rotating-control-plane-tls-credentials.md
- linkerd.io/content/2.9/tasks/manually-rotating-control-plane-tls-credentials.md
> Update yq to v4

- linkerd.io/content/2.10/reference/proxy-configuration.md
- linkerd.io/content/2.9/reference/proxy-configuration.md
> Emphasize "overriding" behavior (#942)

- linkerd.io/content/blog/introduccion-al-service-mesh-con-linkerd.md
* Remove accented character from frontmatter title
> Update URL to remove accent

- linkerd.io/content/heroes/_index.md
> Hero page copy edit

- linkerd.io/layouts/partials/heroes/heroes-section.html
- linkerd.io/layouts/partials/heroes/top-hero.html
> Reduce spacing between sections in heroes page

- linkerd.io/content/blog/march-linkerd-community-meeting.md
* Added link to CNCF meetup page
> Add April community link to blog post

- linkerd.io/content/anchor/_index.md
> fix: add meta to anchors

- netlify.toml
> * Update netlify.toml to use correct directory

- linkerd.io/content/2.10/reference/architecture.md
- linkerd.io/content/2.10/tasks/upgrade.md
- linkerd.io/content/faq/_index.md
> Update to "linkerd viz" command

- linkerd.io/content/get-involved/_index.md
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
> Fix typo in Get Involved page

- .github/workflows/publish.yml
- CONTRIBUTING.md
- README.md
- linkerd.io/layouts/partials/footer.html
- linkerd.io/layouts/partials/footer_old.html
* Updated github publish action to use `main` instead of `master`
> Update publish workflow to use main branch

- linkerd.io/content/2.10/tasks/troubleshooting.md
Related PR https://github.com/linkerd/linkerd2/pull/5943
Related Issue https://github.com/linkerd/linkerd2/issues/5718
Signed-off-by: Szymon Gibała <szymongib@gmail.com>
> Document new checks added as part of #5943

- linkerd.io/content/_index.md
> Tweet updates on homepage

- linkerd.io/content/blog/announcing-linkerd-2-10.md
Is this kind of change acceptable?
Sorry for bothering you.
> Update my GitHub username 

- linkerd.io/assets/scss/_navbar.scss
Closes https://github.com/BuoyantIO/website/issues/236
> Fix: navbar vertically align items

- linkerd.io/content/2.10/features/protocol-detection.md
> update galera replication instructions

- linkerd.io/content/2.10/tasks/installing-multicluster.md
- linkerd.io/content/2.9/tasks/installing-multicluster.md
* Removed server path from relative link
* Closes #1061 
> Fix trust anchor link

- linkerd.io/content/blog/introducing-fuzz-testing-to-linkerd.md
> fix report link

- linkerd.io/content/2.10/tasks/troubleshooting.md
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
> Fix a typo in 2.10/tasks/troubleshooting

- linkerd.io/content/dashboard/cfp-announcement.md
> CFP Announcement

- linkerd.io/content/dashboard/cfp-announcement.md
* Change post date to 5.18.2021
> Update CFP dashboard post date

- linkerd.io/assets/js/search.js
- linkerd.io/assets/scss/styles.scss
- linkerd.io/config.toml
- linkerd.io/content/blog/introducing-fuzz-testing-to-linkerd.md
- linkerd.io/layouts/alias.html
- linkerd.io/layouts/blog/list.html
- linkerd.io/layouts/blog/single.html
- linkerd.io/layouts/partials/blog/adopter-banner.html
- linkerd.io/layouts/partials/pagination.html
- linkerd.io/themes/buoyant/assets/scss/styles-base.scss
- linkerd.io/themes/buoyant/layouts/partials/related-card.html
Updates on https://github.com/linkerd/website/pull/1079
Closes Closes https://github.com/BuoyantIO/website/issues/240
> Blog List and Detail Updates

- linkerd.io/content/dashboard/may-linkerd-online-community-meeting.md
> May Community Meeting

- linkerd.io/content/service-mesh-glossary/_index.md
* Used absolute URLs like we do in the rest of the files to ensure that the link checks pass
> Update the links in the SMG file so CI will pass

- linkerd.io/content/blog/linkerd-vs-istio-benchmarks.md
> change benchmark blost thumbnail and og:image to latency graph

- linkerd.io/content/2.10/reference/proxy-metrics.md
> Add identity metrics description

- linkerd.io/content/2.10/tasks/using-ingress.md
Wanted to reference the Buoyant article on integrating with Emissary as it provides the same information with more detail.
This time using the correct branch ;)
> Referenced Buoyant article on Emissary.

- linkerd.io/content/2.10/tasks/manually-rotating-control-plane-tls-credentials.md
- linkerd.io/content/2.9/tasks/manually-rotating-control-plane-tls-credentials.md
> Add instructions for using helm on "Manually Rotating Control Plane TLS Credentials" page

- linkerd.io/content/blog/announcing-junes-linkerd-heroes.md
@CathPag tagging  you here to have a look.
> Fix typo in recent blogpost

- linkerd.io/content/heroes/_index.md
- linkerd.io/content/support-training.md
* Add github URLs for June heroes
* remove extra line
> Fix some lints

- linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-vi-staging-microservices-without-the-tears.md
Without that, the link does not render and the text shows up literally.
Signed-off-by Dileep Reddem <dileepreddyr@gmail.com>
> Correcting hyperlink in blog

- linkerd.io/content/blog/june-linkerd-community-meeting-recap.md
@C-Mejlak, could you help bring this through the finish line? Thumbnail is below
> June Linkerd community meeting recap blog

- linkerd.io/content/blog/multicluster-kubernetes-with-service-mirroring.md
This commit updates "cluster" to "cross-cluster" in the service
mirroring section.
Fixes #1157
Signed-off-by: Ujjwal Goyal <importujjwal@gmail.com>
> Minor fixes to multicluster blog

- linkerd.io/data/extension-list.yaml
> alphabetize list and remove redundant "linkerd-"

- linkerd.io/content/dashboard/august-2021-linkerd-online-community-meeting.md
* Added markdown for dashboard entry
> add august community meeting announcement

- linkerd.io/layouts/_default/baseof.html
- linkerd.io/layouts/partials/meta.html
Added back the google tag manager tag `GTM-PXBDGKJ` because the one added by segment is not tracking traffic appropriately.
> added back GTM-PXBDGKJ

- linkerd.io/content/blog/august-linkerd-community-meeting-recap.md
We need to get this over the finish line. Thumbnail is below.
> August community meeting recap

- linkerd.io/content/2.11/tasks/troubleshooting.md
Followup to #1185
Copy the `linkerd-buoyant` troubleshouting docs to the 2.11 branch
> Add a linkerd-buoyant section to troubleshooting (2.11)

- linkerd.io/content/support-training.md
Shoulda been more careful. Fix grammar and improve wording.
> wordsmith training page

- linkerd.io/content/2.11/tasks/troubleshooting.md
The following healthcheck hints had no corresponding help section in the troubleshooting page:
```
l5d-cluster-networks-cidr
l5d-cp-proxy-cli-version
l5d-cp-proxy-healthy
l5d-cp-proxy-version
l5d-policy-validator-webhook-cert-not-expiring-soon
l5d-policy-validator-webhook-cert-valid
linkerd-opaque-ports-definition
```
We add sections for each of these items.
> Add missing hint anchors help

- linkerd.io/content/2.11/tasks/restricting-access.md
> Add Restricting Access To Services tutorial

- linkerd.io/content/2.11/tasks/upgrade.md
Added the upgrade notes and breaking changes.
> Add upgrade notes for 2.11

- linkerd.io/content/2.10/features/protocol-detection.md
- linkerd.io/content/2.11/features/protocol-detection.md
- linkerd.io/content/2.11/features/server-policy.md
> add policy feature doc; improve protocol detection doc

- linkerd.io/assets/scss/styles.scss
- linkerd.io/layouts/partials/homepage/foundation-member-banner.html
- linkerd.io/themes/buoyant/assets/scss/styles-base.scss
> fix: footer logo and blog images sizing

- linkerd.io/layouts/partials/docs.html
Link to the latest version of the specific docs page that you're on.
> fix latest version links

- linkerd.io/content/2.11/features/cni.md
Some people have been confused by the fact that they still need their own CNI plugin. Make that clear, and do some other cleanup.
> clean up CNI docs

- linkerd.io/content/2.11/tasks/restricting-access.md
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
> Fix a typo in 2.11/tasks/restricting-access.md

- linkerd.io/content/what-is-a-service-mesh/_index.md
- linkerd.io/layouts/partials/sidebar-2.html
> Add "What is a service mesh?" section

- linkerd.io/content/2.11/features/automatic-mtls.md
- linkerd.io/content/what-is-a-service-mesh/_index.md
> wordsmithing and fixing of FAQ schemata

- linkerd.io/content/dashboard/dec-2021-linkerd-online-community-meeting.md
> Add December meetup to the dashboard

- linkerd.io/content/blog/december-linkerd-community-meeting-recap.md
> fix author

- linkerd.io/content/ambassadors/_index.md
> Update Steve Gray's job title

- linkerd.io/content/blog/linkerd-service-account-tokens.md
> fix: markdown formatting

- linkerd.io/content/blog/the-service-mesh-in-2022.md
Signed-off-by: Kevin Ingelman <ki@buoyant.io>
> Fix typo in service mesh in 2022 post

- run.linkerd.io/public/install
- run.linkerd.io/public/install-edge
Closes #1282
Tested locally 👍🏻
> fix(install): fix usage of --proto curl option

- linkerd.io/content/2.11/tasks/install-helm.md
This back-ports the install instructions from the 2.12 branch (#1244) into the 2.11 branch, specifically for the edge helm charts.
> Update helm install instructions to account for edge changes

- linkerd.io/content/2.11/tasks/upgrade.md
Including a note about re-linking clusters after upgrading the multicluster extension.
> Add upgrade notes for extensions

- linkerd.io/content/2.11/tasks/automatically-rotating-webhook-tls-credentials.md
> viz -> jaeger

- linkerd.io/content/2.11/getting-started/_index.md
- linkerd.io/content/2.11/tasks/extensions.md
> remove Buoyant Cloud commands from getting started

- run.linkerd.io/public/index.html
This applies some auto formatting as well.
> Update run.linkerd.io to point to stable 2.11

- linkerd.io/content/heroes/_index.md
Signed-off-by: Ali Ariff <ali.ariff12@gmail.com>
> Fix my github url

- linkerd.io/content/blog/linkerd-multi-cluster-failover.md
> add closing parenthesis to failover blog post

- linkerd.io/content/2.11/tasks/extensions.md
> Add missing https:// to URL

- linkerd.io/content/2.11/tasks/installing-multicluster.md
> fix configuration options link for helm multicluster install

- linkerd.io/content/2.11/tasks/using-ingress.md
- Fixed links to Traefik 1.x, Traefik 2.x and Ambassador.
> Fix links to headers

- linkerd.io/content/2.10/tasks/extensions.md
- linkerd.io/content/2.11/features/protocol-detection.md
- linkerd.io/content/2.11/getting-started/_index.md
- linkerd.io/content/2.11/tasks/extensions.md
- linkerd.io/content/2.11/tasks/multicluster.md
- linkerd.io/data/extension-list.yaml
> remove / further tone down bcloud references

- linkerd.io/content/blog/architecting-multicluster.md
When I was reading the article I found some improvements
> Improve reading flow on architecting multicluster post

- linkerd.io/content/2.10/tasks/graceful-shutdown.md
- linkerd.io/content/2.11/tasks/graceful-shutdown.md
> document shutdown endpoint

- linkerd.io/data/extension-list.yaml
I do not know what `ScreenshotFileName` is, so I used `unknown.png` 😄
> add EasyAuth extension to extension list

- linkerd.io/layouts/partials/meta.html
> make rel=canonical links to latest docs versions

- linkerd.io/content/2.10/tasks/multicluster.md
- linkerd.io/content/2.11/tasks/multicluster.md
- linkerd.io/content/2.9/tasks/multicluster.md
- linkerd.io/content/2.9/tasks/using-ingress.md
The four links below were broken. It appears we attempted to convert them to relative links and missed removing the domain.
Signed-off-by: Jeremy Chase <jeremy.chase@gmail.com>
> Fix broken relative links

- linkerd.io/config.toml
- linkerd.io/content/_index.md
- linkerd.io/content/blog/linkerd-210-and-extensions.md
- linkerd.io/content/blog/linkerd-steering-committee.md
- linkerd.io/content/blog/security-audit-2022.md
- linkerd.io/layouts/partials/homepage/featured-blogs.html
- linkerd.io/layouts/partials/homepage/stats-list.html
> bring homepage into modern times

- linkerd.io/content/2.11/tasks/install-helm.md
- linkerd.io/content/2.11/tasks/install.md
* Point out that Helm is recommended for production installations.
* Remove multi-stage instructions.
* Wordsmithing.
> improve installation guide

- linkerd.io/data/cli-2-12.yaml
Regenerated by running `linkerd doc`
Closes #1419 
> update linkerd cli docs

- linkerd.io/content/2.12/reference/cli/repair.md
> remove repair page

- linkerd.io/content/2.11/tasks/install-helm.md
- linkerd.io/content/2.11/tasks/install.md
- linkerd.io/content/2.12/tasks/install-helm.md
- linkerd.io/content/2.12/tasks/install.md
- linkerd.io/content/2.12/tasks/installing-multicluster.md
This is just picking up some installation-doc wordsmithing of @wmorgan's.
> Merge main into shared/docs/2.12

- linkerd.io/data/cli-2-12.yaml
To pick up https://github.com/linkerd/linkerd2/pull/9241
> update cli doc yaml

- linkerd.io/content/2.12/reference/proxy-metrics.md
> Add inbound/outbound tcp error metrics

- linkerd.io/content/2.12/tasks/configuring-retries.md
- linkerd.io/content/2.12/tasks/configuring-timeouts.md
- linkerd.io/content/2.12/tasks/getting-per-route-metrics.md
> Add note about service profile vs httproute

- linkerd.io/content/_index.md
> Change the banner to point to the 2.12 announcement

- linkerd.io/content/2.12/features/server-policy.md
> improve policy feature doc

- linkerd.io/content/2.12/features/dashboard.md
- linkerd.io/content/2.12/tasks/exporting-metrics.md
Update to the world of linkerd-viz and no Grafana
> clean up metrics documentation

- linkerd.io/content/2.12/reference/authorization-policy.md
> fix field names in policy reference

- linkerd.io/content/2.12/overview/_index.md
- linkerd.io/content/2.12/tasks/automatically-rotating-control-plane-tls-credentials.md
- linkerd.io/content/2.12/tasks/upgrade.md
- linkerd.io/content/edge/_index.md
* Pull in updates to upgrade doc from 2.11
* Clean up Overview
* Clean up issuer cert rotation
> lots of doc updates

- linkerd.io/content/2.12/tasks/gitops.md
Changes versions to make this work, and removes obsolete note.
Blocked by linkerd/linkerd-examples#272
> Update argocd/gitops doc

- linkerd.io/content/2.12/tasks/gitops.md
Fixes #1503, but should probably be merged the same time as https://github.com/linkerd/linkerd-examples/pull/272 for the versions to match on both sides.
Signed-off-by: Dominik Táskai <dominik.taskai@leannet.eu>
> Update control-plane version in snippet.

- linkerd.io/content/2.12/tasks/automatically-rotating-control-plane-tls-credentials.md
Added backslash to command as execution fails otherwise
> added missing backslash

- linkerd.io/content/2.12/tasks/using-ingress.md
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
> Fix the format in using-ingress.md

- linkerd.io/static/uploads/sma-2022-12.ics
> Add sma-2022-12 ICS file

- linkerd.io/static/uploads/sma-2022-12.ics
> Fix SMA 2022-12 ICS

- linkerd.io/layouts/partials/footer.html
> tweak footer and add scarf analytics

- linkerd.io/content/2.12/features/nft.md
> proxyInit.mode -> proxyInit.iptablesMode

- linkerd.io/content/blog/20221122-startup-deep-dive.md
> Augh. Can't change the title without a redirect. :facepalm:

- linkerd.io/content/2.12/reference/cli/_index.md
- linkerd.io/content/2.12/tasks/_index.md
https://linkerd.io/2.12/reference/cli/get/ => https://linkerd.io/2.12/reference/cli/
https://linkerd.io/2.12/tasks/upgrade-multicluster/ => https://linkerd.io/2.12/tasks/
https://linkerd.io/2.12/tasks/enabling-addons/ => https://linkerd.io/2.12/tasks/
> More redirects

- linkerd.io/content/2.12/reference/authorization-policy.md
> add note about httproute precedence and cleanup

- linkerd.io/content/support-training.md
Signed-off-by: Chetan Deshmukh <cdeshmukh@infracloud.io>
> Updating Linkerd capabilities landing page

- linkerd.io/content/2.12/reference/authorization-policy.md
I made a typo on the previous PR 🤦
> Update authorization policy documenation with wildcard support - fix typo

- linkerd.io/config.toml
- linkerd.io/content/blog/announcing-linkerd-day-2023.md
In theory, the external URL should cause the link to open in a
separate window.
> Add Linkerd Day EU 2023 entry to the Community menu

- linkerd.io/static/uploads/sma-2023/2023-03.ics
> Add the calendar link for 2023-03 SMA

- linkerd.io/content/support-training.md
Add the "Providers" section to the Support & Training page.
> Clean up internals. Add the Providers section.

- linkerd.io/content/2-edge/getting-started/_index.md
- linkerd.io/content/2.10/getting-started/_index.md
- linkerd.io/content/2.11/getting-started/_index.md
- linkerd.io/content/2.12/getting-started/_index.md
- linkerd.io/content/2.9/getting-started/_index.md
- linkerd.io/layouts/shortcodes/trylpt.html
Tweak words to be closer to my view of reality
> update messaging around prod/non-prod/community

- linkerd.io/content/2-edge/tasks/configuring-dynamic-request-routing.md
- linkerd.io/content/2-edge/tasks/configuring-header-based-routing.md
You can check the render [here](https://github.com/linkerd/website/blob/7cbb84c77df9ba7cbfd00e0d70614ff546063075/linkerd.io/content/2-edge/tasks/configuring-dynamic-request-routing.md)
> Add header-based routing tutorial

- linkerd.io/content/support-training.md
Signed-off-by: Chetan Deshmukh <cdeshmukh@infracloud.io>
> updating InfraCloud's suport page details

- linkerd.io/content/blog/2023/0525-osm-migration.md
- linkerd.io/content/blog/2023/0526-osm-migration.md
- linkerd.io/content/blog/_index.md
> OSM migration blog post

- linkerd.io/content/2-edge/tasks/distributed-tracing.md
- linkerd.io/content/2.13/tasks/distributed-tracing.md
> Distributed tracing fixups

- linkerd.io/content/blog/2023/0221-linkerd-and-ingress.md
> Fix wrong annotation! 🤦‍♂️

- linkerd.io/content/faq/_index.md
> allow for enterprise distributions in the FAQ

- linkerd.io/content/2-edge/tasks/linkerd-smi.md
- linkerd.io/content/2.10/tasks/linkerd-smi.md
- linkerd.io/content/2.11/tasks/linkerd-smi.md
- linkerd.io/content/2.12/tasks/linkerd-smi.md
- linkerd.io/content/2.13/tasks/linkerd-smi.md
Fixed a minor typo.
faling -> failing
> Fix typo faling -> failing

- linkerd.io/content/blog/2023/0725-linkerd-hero.md
Second time that local previews have worked and the real one doesn't. WTFO.
> Fix July 2023 hero URL/images

- linkerd.io/content/2-edge/features/cni.md
- linkerd.io/content/2-edge/features/http-grpc.md
- linkerd.io/content/2-edge/features/nft.md
- linkerd.io/content/2-edge/features/request-routing.md
- linkerd.io/content/2-edge/features/server-policy.md
- linkerd.io/content/2-edge/features/traffic-split.md
- linkerd.io/content/2-edge/tasks/configuring-dynamic-request-routing.md
- linkerd.io/content/2-edge/tasks/configuring-per-route-policy.md
- linkerd.io/content/2-edge/tasks/using-ingress.md
Ported #1648, #1642 to the 2-edge docs
> Port 2.13 changes that were missed in 2-edge

- linkerd.io/content/2.13/reference/cli/prune.md
- linkerd.io/content/2.14/reference/cli/prune.md
- linkerd.io/layouts/partials/1/sidebar.html
- linkerd.io/layouts/shortcodes/cli.html
Also added missing entry in linkerd 1's sidebar :man_shrugging:
> Fixed CLI reference for 2.14

- linkerd.io/content/2.14/tasks/using-ingress.md
previous PR adding it to a future version of the docs is #1673 
this adds ngrok to the current version of the docs.
> fix: adding ngrok to 2.14 docs

- linkerd.io/content/going-to-production/_index.md
> Fixed typo in Going to Production

- linkerd.io/content/releases/release_matrix.json
- linkerd.io/content/releases/release_matrix.yaml
- linkerd.io/data/releases/release_matrix.json
> Update version matrix

- .devcontainer/on-create.sh
Bumping Hugo version to pick up a few security fixes.
> Update Hugo version to 0.121.2

- linkerd.io/content/releases/release_matrix.json
- linkerd.io/content/releases/release_matrix.yaml
- linkerd.io/data/releases/release_matrix.json
> Update release matrix for 2.14.10

- linkerd.io/data/cli-2-14.yaml
> Include protocol-detection annotations in 2.14 docs.

- linkerd.io/content/blog/2024/0312-edge-release-roundup.md
> Edge Release Roundup 2024-03

- linkerd.io/content/_index.md
> Trim metadata (we're getting dinged 'cause it's too long).

- linkerd.io/content/what-is-a-service-mesh/_index.md
Shorten the metadata, and tweak the first paragraph to read a little more nicely.
> Metadata (and initial body text) tweak to "what is a service mesh" page

- linkerd.io/content/2-edge/tasks/upgrade.md
- linkerd.io/content/2.15/tasks/upgrade.md
The former is no longer supported in latest kubectl versions.
> Replace kubectl's `--prune-whitelist` with `--prune-allowlist`

- linkerd.io/content/releases/_index.md
Updated latest version of BEL on the releases page.
> Update latest version of BEL

- linkerd.io/layouts/index.searchindex.json
Search index output:
https://deploy-preview-1806--linkerdio.netlify.app/search.json
> Update search index to always use the latest stable version

- linkerd.io/content/blog/2024/0805-edge-release-roundup.md
> Just happened to notice this typo... sigh.

- linkerd.io/content/2.15/reference/external-workload.md
> Have a correct v1beta1 ExternalWorkload in the docs

- linkerd.io/content/2-edge/tasks/extensions.md
- linkerd.io/content/2.14/tasks/extensions.md
- linkerd.io/content/2.15/tasks/extensions.md
- linkerd.io/content/2.16/tasks/extensions.md
Fixes https://github.com/linkerd/linkerd2/issues/12142
> Note that you mustn't install extensions in the linkerd namespace.

- linkerd.io/content/2.14/tasks/books.md
- linkerd.io/content/2.15/tasks/books.md
- linkerd.io/content/2.16/tasks/books.md
Fixes https://github.com/linkerd/linkerd2/issues/12825
@southsidedean, it'd be great for you to check this out too. 🙂 
> Further updates to the per-route metrics doc

- linkerd.io/content/2-edge/tasks/using-ingress.md
- linkerd.io/content/2.16/tasks/using-ingress.md
> Bring the change from #1801 into 2.16 and 2-edge docs

- linkerd.io/layouts/partials/meta.html
> Whoops. I missed the OpenGraph social image. :man_facepalming:

- linkerd.io/data/announcement_banner.yaml
- **Switch banner to SMA instead of LUAR**
- **Re-add spaces**
> Switch banner

- linkerd.io/content/blog/2018/0918-announcing-linkerd-2-0/index.md
- linkerd.io/content/blog/2018/1023-a-linkerd-2-0-deep-dive-unboxing-debugging-and-monitoring-kubernetes-services-on-azure/index.md
- linkerd.io/content/blog/2018/1102-debugging-node-js-on-kubernetes-with-linkerd/index.md
- linkerd.io/content/blog/2018/1105-debugging-and-monitoring-your-kubernetes-services-with-linkerd-2-0/index.md
- linkerd.io/content/blog/2018/1113-debugging-node-services-in-kubernetes-with-linkerd-2-0/index.md
- linkerd.io/content/blog/2018/1206-announcing-linkerd-2-1/index.md
- linkerd.io/content/blog/2019/0212-announcing-linkerd-2-2/index.md
- linkerd.io/content/blog/2019/0222-how-we-designed-retries-in-linkerd-2-2/index.md
Added missing slugs in a few blog posts.
> Fix broken blog links

- linkerd.io/assets/scss/app/_ambassadors.scss
- linkerd.io/layouts/community/ambassadors.html
Added missing highlight to the emeritus card on the ambassadors page.
https://deploy-preview-1867--linkerdio.netlify.app/community/ambassadors/
> Highlight emeritus card

- linkerd.io/content/releases/_index.md
Updated latest BEL version on the releases page:
https://deploy-preview-1871--linkerdio.netlify.app/releases/
> Update latest BEL version

- README.md
- linkerd.io/config/_default/params.yaml
- linkerd.io/layouts/_default/baseof.html
- linkerd.io/layouts/partials/hugo-version-check.html
Added check that will fail the build if the minimum version of Hugo is not met.
> Add minimum Hugo version check

- linkerd.io/config/_default/menu.yaml
- linkerd.io/config/_default/params.yaml
- linkerd.io/content/community/ambassadors/_index.md
- linkerd.io/data/announcement.yaml
- linkerd.io/layouts/partials/main-announcement.html
https://deploy-preview-1879--linkerdio.netlify.app/community/ambassadors/
> Add link to "Become an Ambassador" page

- linkerd.io/content/blog/2019/0524-smi/index.md
> This was not written in May of 2024. :)

- linkerd.io/content/2.16/reference/k8s-versions.md
> Update 2.16 K8s versions (this got missed when 2.16 was released, sigh)

- linkerd.io/content/2-edge/overview/_index.md
- linkerd.io/content/2.12/overview/_index.md
- linkerd.io/content/2.13/overview/_index.md
- linkerd.io/content/2.14/overview/_index.md
- linkerd.io/content/2.15/overview/_index.md
- linkerd.io/content/2.16/overview/_index.md
- linkerd.io/content/2.17/overview/_index.md
> Fix a typo originally covered in PR#1780

- linkerd.io/content/tests/markdown.md
- linkerd.io/layouts/_default/_markup/render-codeblock-mermaid.html
- linkerd.io/layouts/partials/body-close.html
Added Mermaid support for future use.
> Mermaid support

- linkerd.io/content/dashboard/_index.md
- linkerd.io/layouts/dashboard/list.json
https://deploy-preview-1957--linkerdio.netlify.app/dashboard/index.json
> Add missing json feed for dashboard

- linkerd.io/content/blog/2025/0424-linkerd-benchmarks/index.md
As discussed with Flynn and Catherine.
> Rephrase benchmark blog post.

- linkerd.io/layouts/index.searchindex.json
Improve search result by including the full content of doc in the search results.
> Include full content in search index

- linkerd.io/content/blog/_index.md
> Make the Great Sidecar Debate a featured blog post

- linkerd.io/content/meetup-in-a-box/_index.md
**Preview:** https://deploy-preview-2024--linkerdio.netlify.app/meetup-in-a-box/
> Remove swag button from meetup page
